In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)
pd.set_option("display.max_rows", 200)

print("Libraries loaded successfully.")

Libraries loaded successfully.

In [2]:
#Loading DES and UPAG processed data
DES_PATH = "../data/processed/crop_yield/des_apy_2013_14_2022_23.csv"
UPAG_PATH = "../data/processed/crop_yield/upag_2022_23_2024_25.csv"

des = pd.read_csv(DES_PATH)
upag = pd.read_csv(UPAG_PATH)

print("DES shape :", des.shape)
print("UPAg shape:", upag.shape)

print("\nDES columns:")
print(des.columns.tolist())

print("\nUPAg columns:")
print(upag.columns.tolist())

DES shape : (85920, 16)
UPAg shape: (9384, 16)

DES columns:
['state', 'state_code', 'district', 'district_code', 'crop', 'crop_source_name', 'crop_code', 'crop_type', 'season', 'year', 'area_ha', 'production_tonnes', 'yield_tonnes_ha', 'yield_kg_ha', 'yield_quintal_acre', 'data_source']

UPAg columns:
['state', 'state_code', 'district', 'district_code', 'census_code', 'crop', 'crop_source_name', 'year', 'area_lakh_ha', 'area_ha', 'production_lakh_tonnes', 'production_tonnes', 'yield_kg_ha', 'yield_tonnes_ha', 'yield_quintal_acre', 'data_source']

In [3]:
#Selecting 2022-23
TARGET_YEAR = "2022-2023"

des_2022 = des[
    des["year"] == TARGET_YEAR
].copy()

upag_2022 = upag[
    upag["year"] == TARGET_YEAR
].copy()

print("DES 2022-23 :", des_2022.shape)
print("UPAg 2022-23:", upag_2022.shape)

DES 2022-23 : (9742, 16)
UPAg 2022-23: (3128, 16)

In [4]:
#Basic crop info
print("DES crops:")
print(
    des_2022["crop"]
    .value_counts()
    .sort_index()
)

print("\nUPAg crops:")
print(
    upag_2022["crop"]
    .value_counts()
    .sort_index()
)

DES crops:
crop
Arhar/Tur     637
Bajra         572
Gram          548
Groundnut     961
Jowar         652
Maize        1599
Ragi          426
Rice         1578
Soyabean      430
Sugarcane     507
Urad         1269
Wheat         563
Name: count, dtype: int64

UPAg crops:
crop
Maize    782
Rice     782
Urad     782
Wheat    782
Name: count, dtype: int64

In [5]:
#Validation crops
VALIDATION_CROPS = [
    "Rice",
    "Wheat",
    "Maize",
    "Urad"
]

print("Validation crops:")
for crop in VALIDATION_CROPS:
    print("-", crop)

Validation crops:
- Rice
- Wheat
- Maize
- Urad

In [6]:
#Checking DES season values
print("DES seasons for validation crops:\n")

season_distribution = (
    des_2022[
        des_2022["crop"].isin(VALIDATION_CROPS)
    ]
    .groupby(["crop", "season"])
    .agg(
        district_count=("district_code", "nunique"),
        observation_count=("district_code", "size"),
        total_area_ha=("area_ha", "sum"),
        total_production_tonnes=("production_tonnes", "sum")
    )
    .reset_index()
    .sort_values(
        ["crop", "district_count"],
        ascending=[True, False]
    )
)

display(season_distribution)

DES seasons for validation crops:

     crop      season  district_count  observation_count  total_area_ha  total_production_tonnes
1   Maize      Kharif             552                552   7.491378e+06             2.241874e+07
4   Maize       Total             393                393   7.304143e+06             2.852768e+07
2   Maize        Rabi             351                351   2.191371e+06             1.232166e+07
3   Maize      Summer             214                214   5.062171e+05             2.641566e+06
0   Maize      Autumn              74                 74   3.144490e+05             8.780856e+05
6   Maize      Winter              10                 10   2.540000e+02             6.951000e+02
5   Maize  Whole Year               5                  5   8.820000e+01             2.586700e+02
8    Rice      Kharif             485                485   2.855873e+07             8.812963e+07
11   Rice       Total             363                363   3.248316e+07             9.834238e+07
10   Rice      Summer             246                246   3.119536e+06             1.083685e+07
12   Rice      Winter             193                193   1.311415e+07             3.796920e+07
7    Rice      Autumn             176                176   1.550800e+06             3.913987e+06
9    Rice        Rabi             115                115   4.137540e+06             1.410341e+07
14   Urad      Kharif             488                488   3.024839e+06             1.788590e+06
17   Urad       Total             338                338   2.959712e+06             2.117207e+06
15   Urad        Rabi             239                239   7.659454e+05             7.165234e+05
16   Urad      Summer             161                161   1.432716e+05             1.516973e+05
18   Urad      Winter              28                 28   5.711300e+04             2.204850e+04
13   Urad      Autumn              15                 15   1.292100e+04             3.838900e+03
20  Wheat        Rabi             537                537   3.517930e+07             1.284740e+08
23  Wheat  Whole Year               9                  9   2.370000e+03             5.880000e+03
21  Wheat      Summer               7                  7   2.230000e+02             3.452000e+02
19  Wheat      Kharif               5                  5   2.600000e+01             5.300000e+01
22  Wheat       Total               5                  5   1.460000e+03             3.022000e+03

In [ ]:
#Defininf helper functions
def safe_percentage_difference(des_value, upag_value):
    """
    Calculates absolute percentage difference using DES as denominator. Returns NaN when DES value is zero.
    """
    
    des_value = pd.to_numeric(des_value, errors="coerce")
    upag_value = pd.to_numeric(upag_value, errors="coerce")
    
    result = (
        (des_value - upag_value).abs()
        / des_value.abs()
        * 100
    )
    
    result = result.mask(des_value == 0)
    
    return result

In [8]:
def calculate_comparison(
    des_df,
    upag_df,
    des_filter=None,
    crop=None,
    aggregation_name=None
):
    """
    Merge DES and UPAg data and calculate area, production and yield differences.
    """
    
    d = des_df.copy()
    u = upag_df.copy()
    
    if des_filter is not None:
        d = d[des_filter].copy()
    
    if crop is not None:
        d = d[d["crop"] == crop].copy()
        u = u[u["crop"] == crop].copy()
    
    comparison = pd.merge(
        d,
        u,
        on=[
            "state_code",
            "district_code",
            "crop"
        ],
        how="inner",
        suffixes=("_des", "_upag")
    )
    
    if aggregation_name is not None:
        comparison["des_representation"] = aggregation_name
    
    comparison["area_difference"] = (
        comparison["area_ha_des"]
        - comparison["area_ha_upag"]
    )
    
    comparison["production_difference"] = (
        comparison["production_tonnes_des"]
        - comparison["production_tonnes_upag"]
    )
    
    comparison["yield_difference"] = (
        comparison["yield_kg_ha_des"]
        - comparison["yield_kg_ha_upag"]
    )
    
    comparison["area_difference_pct"] = safe_percentage_difference(
        comparison["area_ha_des"],
        comparison["area_ha_upag"]
    )
    
    comparison["production_difference_pct"] = safe_percentage_difference(
        comparison["production_tonnes_des"],
        comparison["production_tonnes_upag"]
    )
    
    comparison["yield_difference_pct"] = safe_percentage_difference(
        comparison["yield_kg_ha_des"],
        comparison["yield_kg_ha_upag"]
    )
    
    return comparison

In [9]:
#Four specific problematic examples
EXAMPLES = [
    ("Maize", "Tamil Nadu", "Thoothukkudi"),
    ("Rice", "Tripura", "West Tripura"),
    ("Urad", "Tamil Nadu", "Mayiladuthurai"),
    ("Wheat", "Jammu And Kashmir", "Budgam")
]

In [ ]:
#DES Examples
for crop, state, district in EXAMPLES:
    
    print(f"DES | {crop} | {state} | {district}")
    
    temp = des_2022[
        (des_2022["crop"] == crop) &
        (des_2022["state"] == state) &
        (des_2022["district"] == district)
    ].copy()
    
    display(
        temp[
            [
                "state",
                "district",
                "crop",
                "season",
                "area_ha",
                "production_tonnes",
                "yield_kg_ha"
            ]
        ]
        .sort_values("season")
        .reset_index(drop=True)
    )

==========================================================================================
DES | Maize | Tamil Nadu | Thoothukkudi
==========================================================================================

        state      district   crop  season  area_ha  production_tonnes  yield_kg_ha
0  Tamil Nadu  Thoothukkudi  Maize  Kharif      2.0               19.0       9500.0
1  Tamil Nadu  Thoothukkudi  Maize    Rabi  50003.0           176557.0       3531.0
2  Tamil Nadu  Thoothukkudi  Maize   Total  50005.0           176576.0       3531.0

==========================================================================================
DES | Rice | Tripura | West Tripura
==========================================================================================

     state      district  crop  season  area_ha  production_tonnes  yield_kg_ha
0  Tripura  West Tripura  Rice  Autumn     38.0              102.0       2684.0
1  Tripura  West Tripura  Rice  Kharif    176.0              192.0       1091.0
2  Tripura  West Tripura  Rice  Summer   7996.0            28036.0       3506.0
3  Tripura  West Tripura  Rice   Total  23196.0            79725.0       3437.0
4  Tripura  West Tripura  Rice  Winter  14986.0            51395.0       3430.0

==========================================================================================
DES | Urad | Tamil Nadu | Mayiladuthurai
==========================================================================================

        state        district  crop  season  area_ha  production_tonnes  yield_kg_ha
0  Tamil Nadu  Mayiladuthurai  Urad  Kharif     12.0               10.0        833.0
1  Tamil Nadu  Mayiladuthurai  Urad    Rabi  24304.0             5309.0        218.0
2  Tamil Nadu  Mayiladuthurai  Urad   Total  24316.0             5319.0        219.0

==========================================================================================
DES | Wheat | Jammu And Kashmir | Budgam
==========================================================================================

               state district   crop season  area_ha  production_tonnes  yield_kg_ha
0  Jammu And Kashmir   Budgam  Wheat   Rabi   1071.0          2035.1784       1900.0

In [ ]:
#UPAG examples
for crop, state, district in EXAMPLES:
    
    print(f"UPAg | {crop} | {state} | {district}")
    
    temp = upag_2022[
        (upag_2022["crop"] == crop) &
        (upag_2022["state"] == state) &
        (upag_2022["district"] == district)
    ].copy()
    
    display(
        temp[
            [
                "state",
                "district",
                "crop",
                "area_ha",
                "production_tonnes",
                "yield_kg_ha"
            ]
        ]
        .reset_index(drop=True)
    )

==========================================================================================
UPAg | Maize | Tamil Nadu | Thoothukkudi
==========================================================================================

        state      district   crop  area_ha  production_tonnes  yield_kg_ha
0  Tamil Nadu  Thoothukkudi  Maize  50000.0           177000.0       3531.0

==========================================================================================
UPAg | Rice | Tripura | West Tripura
==========================================================================================

     state      district  crop  area_ha  production_tonnes  yield_kg_ha
0  Tripura  West Tripura  Rice  23000.0            80000.0       3437.0

==========================================================================================
UPAg | Urad | Tamil Nadu | Mayiladuthurai
==========================================================================================

        state        district  crop  area_ha  production_tonnes  yield_kg_ha
0  Tamil Nadu  Mayiladuthurai  Urad  24000.0             5000.0        219.0

==========================================================================================
UPAg | Wheat | Jammu And Kashmir | Budgam
==========================================================================================

               state district   crop  area_ha  production_tonnes  yield_kg_ha
0  Jammu And Kashmir   Budgam  Wheat   1000.0             2000.0       1900.0

In [12]:
#Creating DES season wise comparisons
ALL_SEASONS = sorted(
    des_2022["season"]
    .dropna()
    .unique()
)

print("DES seasons:")
print(ALL_SEASONS)

DES seasons:
['Autumn', 'Kharif', 'Rabi', 'Summer', 'Total', 'Whole Year', 'Winter']

In [13]:
season_comparisons = []

for crop in VALIDATION_CROPS:
    
    for season in ALL_SEASONS:
        
        des_subset = des_2022[
            (des_2022["crop"] == crop) &
            (des_2022["season"] == season)
        ].copy()
        
        if des_subset.empty:
            continue
        
        upag_subset = upag_2022[
            upag_2022["crop"] == crop
        ].copy()
        
        comparison = calculate_comparison(
            des_subset,
            upag_subset,
            aggregation_name=season
        )
        
        if not comparison.empty:
            season_comparisons.append(
                comparison
            )

season_comparisons = pd.concat(
    season_comparisons,
    ignore_index=True
)

print(
    "Total season-level matched observations:",
    len(season_comparisons)
)

Total season-level matched observations: 5009

In [14]:
#Summarizing every season
season_comparison_summary = (
    season_comparisons
    .groupby(
        ["crop", "des_representation"]
    )
    .agg(
        matched_districts=(
            "district_code",
            "nunique"
        ),
        
        median_area_diff_pct=(
            "area_difference_pct",
            "median"
        ),
        
        mean_area_diff_pct=(
            "area_difference_pct",
            "mean"
        ),
        
        median_production_diff_pct=(
            "production_difference_pct",
            "median"
        ),
        
        mean_production_diff_pct=(
            "production_difference_pct",
            "mean"
        ),
        
        median_yield_diff_pct=(
            "yield_difference_pct",
            "median"
        ),
        
        mean_yield_diff_pct=(
            "yield_difference_pct",
            "mean"
        )
    )
    .reset_index()
)

display(
    season_comparison_summary
    .sort_values(
        ["crop", "median_area_diff_pct"]
    )
)

     crop des_representation  matched_districts  median_area_diff_pct  mean_area_diff_pct  median_production_diff_pct  mean_production_diff_pct  median_yield_diff_pct  mean_yield_diff_pct
4   Maize              Total                393              5.060410           24.511288                    1.746725                 13.328732               0.000000         8.520801e-17
1   Maize             Kharif                552             38.082444         5088.757143                   28.354995               2701.436543               0.249004         8.821001e+00
0   Maize             Autumn                 74            100.000000          770.928719                  292.884906               2026.510471              26.891859         5.398953e+01
5   Maize         Whole Year                  5            100.000000          100.000000                  100.000000                100.000000               0.000000         0.000000e+00
6   Maize             Winter                 10            100.000000         4952.027650                 2029.059402               6305.972059              10.838321         1.286528e+01
2   Maize               Rabi                351            203.030303        20538.668156                  188.184438              16673.149493              10.691469         1.797155e+01
3   Maize             Summer                214            658.971407         5113.687624                  714.627033               5361.115034              17.221027         3.096781e+01
11   Rice              Total                363              0.321960            2.770906                    0.106164                  1.409153               0.000000         2.202852e-01
8    Rice             Kharif                485              2.540731          111.758602                    1.729400                272.771631               0.000000         6.703368e+00
12   Rice             Winter                193             28.886741           51.642490                   29.470126                 52.526205               2.045944         3.963866e+00
9    Rice               Rabi                115            141.637276        15456.069720                  152.684776              14130.497835               5.395683         1.566896e+01
7    Rice             Autumn                176            952.444271        17319.558652                 1402.588911              27585.976536              20.351094         3.641408e+01
10   Rice             Summer                246           1427.514055       106243.859744                 1325.379785              70703.280180              12.066830         1.590733e+01
17   Urad              Total                338             14.857075           40.060564                   26.700305                 48.627406               0.000000         2.958580e-01
18   Urad             Winter                 28             79.554495         2068.514049                  100.000000               1962.161417               1.418378         7.258302e+00
14   Urad             Kharif                488             90.181512         1014.720453                  100.000000                559.021099               0.452489         1.981426e+01
13   Urad             Autumn                 15            100.000000        22898.217625                  100.000000              17338.481662               3.030303         1.180444e+01
15   Urad               Rabi                239            100.000000         7456.805275                  100.000000               4818.775509               4.171240         1.232544e+01
16   Urad             Summer                161            900.000000        91495.091682                  350.450450              69665.162661              24.944072         2.887493e+01
20  Wheat               Rabi                537              0.749780           25.149742                    0.239218                 22.277536               0.000000         2.693632e-04
19  Wheat             Kharif                  5            100.000000         1012.380952                  100.000000               1455.348837               1.074219         1.634844e+00
21  Wheat             Summer                  7            100.000000          100.000000                  100.000000                100.000000               0.000000         0.000000e+00
22  Wheat              Total                  5            100.000000           84.089101                  100.000000                 83.059185               0.000000         0.000000e+00
23  Wheat         Whole Year                  9            100.000000          100.000000                   42.857143                 50.184244               0.000000         0.000000e+00

In [15]:
#Percentage of districts within tolerance
def tolerance_summary(
    comparison_df,
    tolerance
):
    
    rows = []
    
    for (crop, representation), group in comparison_df.groupby(
        ["crop", "des_representation"]
    ):
        
        rows.append({
            "crop": crop,
            "representation": representation,
            "matched": len(group),
            
            "area_within_pct": (
                group["area_difference_pct"] <= tolerance
            ).mean() * 100,
            
            "production_within_pct": (
                group["production_difference_pct"] <= tolerance
            ).mean() * 100,
            
            "yield_within_pct": (
                group["yield_difference_pct"] <= tolerance
            ).mean() * 100
        })
    
    return pd.DataFrame(rows)

In [16]:
tolerance_10 = tolerance_summary(
    season_comparisons,
    10
)

display(
    tolerance_10
    .sort_values(
        ["crop", "area_within_pct"],
        ascending=[True, False]
    )
)

     crop representation  matched  area_within_pct  production_within_pct  yield_within_pct
4   Maize          Total      393        62.595420              77.099237        100.000000
1   Maize         Kharif      552        27.717391              38.043478         76.811594
0   Maize         Autumn       74        10.810811              14.864865         41.891892
2   Maize           Rabi      351         5.698006               7.122507         46.438746
3   Maize         Summer      214         0.467290               1.869159         35.514019
5   Maize     Whole Year        5         0.000000               0.000000        100.000000
6   Maize         Winter       10         0.000000               0.000000         40.000000
11   Rice          Total      363        94.214876              98.071625         99.724518
8    Rice         Kharif      485        63.505155              64.536082         90.515464
12   Rice         Winter      193        30.051813              32.642487         89.119171
7    Rice         Autumn      176         0.568182               1.136364         31.818182
9    Rice           Rabi      115         0.000000               1.739130         66.086957
10   Rice         Summer      246         0.000000               0.000000         42.276423
17   Urad          Total      338        43.491124              36.686391         99.704142
14   Urad         Kharif      488        29.303279              22.336066         72.540984
13   Urad         Autumn       15        20.000000               0.000000         60.000000
18   Urad         Winter       28        17.857143              17.857143         78.571429
15   Urad           Rabi      239        12.552301              12.970711         64.435146
16   Urad         Summer      161         2.484472               2.484472         24.844720
20  Wheat           Rabi      537        71.694600              73.184358        100.000000
19  Wheat         Kharif        5         0.000000               0.000000        100.000000
21  Wheat         Summer        7         0.000000               0.000000        100.000000
22  Wheat          Total        5         0.000000               0.000000        100.000000
23  Wheat     Whole Year        9         0.000000              22.222222        100.000000

In [17]:
#Exact yield agreement
yield_summary = (
    season_comparisons
    .groupby(
        ["crop", "des_representation"]
    )
    .agg(
        matched=("yield_difference", "size"),
        
        exact_yield_matches=(
            "yield_difference",
            lambda x: (x == 0).sum()
        ),
        
        nonzero_yield_differences=(
            "yield_difference",
            lambda x: (x != 0).sum()
        )
    )
    .reset_index()
)

yield_summary["exact_yield_match_pct"] = (
    yield_summary["exact_yield_matches"]
    /
    yield_summary["matched"]
    * 100
)

display(
    yield_summary
    .sort_values(
        ["crop", "exact_yield_match_pct"],
        ascending=[True, False]
    )
)

     crop des_representation  matched  exact_yield_matches  nonzero_yield_differences  exact_yield_match_pct
5   Maize         Whole Year        5                    5                          0             100.000000
4   Maize              Total      393                  391                          2              99.491094
1   Maize             Kharif      552                  258                        294              46.739130
0   Maize             Autumn       74                    6                         68               8.108108
2   Maize               Rabi      351                   19                        332               5.413105
3   Maize             Summer      214                    6                        208               2.803738
6   Maize             Winter       10                    0                         10               0.000000
11   Rice              Total      363                  361                          2              99.449036
8    Rice             Kharif      485                  311                        174              64.123711
12   Rice             Winter      193                   25                        168              12.953368
9    Rice               Rabi      115                    5                        110               4.347826
7    Rice             Autumn      176                    4                        172               2.272727
10   Rice             Summer      246                    1                        245               0.406504
17   Urad              Total      338                  337                          1              99.704142
14   Urad             Kharif      488                  224                        264              45.901639
18   Urad             Winter       28                    8                         20              28.571429
15   Urad               Rabi      239                   62                        177              25.941423
13   Urad             Autumn       15                    2                         13              13.333333
16   Urad             Summer      161                    7                        154               4.347826
21  Wheat             Summer        7                    7                          0             100.000000
22  Wheat              Total        5                    5                          0             100.000000
23  Wheat         Whole Year        9                    9                          0             100.000000
20  Wheat               Rabi      537                  535                          2              99.627561
19  Wheat             Kharif        5                    2                          3              40.000000

In [18]:
#Investigating DES total
total_des = des_2022[
    (
        des_2022["season"]
        .astype(str)
        .str.strip()
        .str.lower()
        == "total"
    ) &
    des_2022["crop"].isin(VALIDATION_CROPS)
].copy()

print(
    "DES Total observations:",
    total_des.shape
)

display(
    total_des[
        [
            "crop",
            "state",
            "district",
            "area_ha",
            "production_tonnes",
            "yield_kg_ha"
        ]
    ].head(20)
)

DES Total observations: (1099, 16)

        crop           state                     district   area_ha  production_tonnes  yield_kg_ha
76200  Maize  Andhra Pradesh        Alluri Sitharama Raju    5644.0            19517.0       3458.0
76204   Rice  Andhra Pradesh        Alluri Sitharama Raju   58705.0           175374.0       2987.0
76208   Urad  Andhra Pradesh        Alluri Sitharama Raju    3023.0             2502.0        828.0
76218  Maize  Andhra Pradesh                   Anakapalli      90.0              688.0       7644.0
76224   Rice  Andhra Pradesh                   Anakapalli   59406.0           186481.0       3139.0
76228   Urad  Andhra Pradesh                   Anakapalli    8857.0             4975.0        562.0
76246  Maize  Andhra Pradesh                Ananthapuramu   27586.0           161542.0       5856.0
76252   Rice  Andhra Pradesh                Ananthapuramu   26995.0           103988.0       3852.0
76259   Urad  Andhra Pradesh                Ananthapuramu     901.0             1105.0       1226.0
76276  Maize  Andhra Pradesh                    Annamayya    3262.0            19707.0       6041.0
76282   Rice  Andhra Pradesh                    Annamayya   15906.0            52418.0       3295.0
76289   Urad  Andhra Pradesh                    Annamayya     241.0              293.0       1216.0
76303  Maize  Andhra Pradesh                      Bapatla   41450.0           473521.0      11424.0
76307   Rice  Andhra Pradesh                      Bapatla  115379.0           480939.0       4168.0
76314   Urad  Andhra Pradesh                      Bapatla   23972.0            36430.0       1520.0
76326  Maize  Andhra Pradesh                     Chittoor    1194.0             7452.0       6241.0
76332   Rice  Andhra Pradesh                     Chittoor   19888.0            62697.0       3153.0
76336   Urad  Andhra Pradesh                     Chittoor     805.0              675.0        839.0
76341  Maize  Andhra Pradesh  Dr. B.R. Ambedkar Konaseema    1154.0            11042.0       9568.0
76344   Rice  Andhra Pradesh  Dr. B.R. Ambedkar Konaseema  126790.0           584636.0       4611.0

In [19]:
#Comparing total against UPAG
total_comparisons = []

for crop in VALIDATION_CROPS:
    
    d = total_des[
        total_des["crop"] == crop
    ].copy()
    
    u = upag_2022[
        upag_2022["crop"] == crop
    ].copy()
    
    if d.empty:
        continue
    
    comparison = calculate_comparison(
        d,
        u,
        aggregation_name="Total"
    )
    
    if not comparison.empty:
        total_comparisons.append(
            comparison
        )

total_comparisons = pd.concat(
    total_comparisons,
    ignore_index=True
)

print(
    "Total matched observations:",
    len(total_comparisons)
)

Total matched observations: 1099

In [ ]:
#Summarizing total
total_summary = (
    total_comparisons
    .groupby("crop")
    .agg(
        matched_districts=(
            "district_code",
            "nunique"
        ),
        
        median_area_diff_pct=(
            "area_difference_pct",
            "median"
        ),
        
        mean_area_diff_pct=(
            "area_difference_pct",
            "mean"
        ),
        
        median_production_diff_pct=(
            "production_difference_pct",
            "median"
        ),
        
        mean_production_diff_pct=(
            "production_difference_pct",
            "mean"
        ),
        
        median_yield_diff_pct=(
            "yield_difference_pct",
            "median"
        ),
        
        mean_yield_diff_pct=(
            "yield_difference_pct",
            "mean"
        )
    )
    .reset_index()
)

display(total_summary)

    crop  matched_districts  median_area_diff_pct  mean_area_diff_pct  median_production_diff_pct  mean_production_diff_pct  median_yield_diff_pct  mean_yield_diff_pct
0  Maize                393              5.060410           24.511288                    1.746725                 13.328732                    0.0         8.520801e-17
1   Rice                363              0.321960            2.770906                    0.106164                  1.409153                    0.0         2.202852e-01
2   Urad                338             14.857075           40.060564                   26.700305                 48.627406                    0.0         2.958580e-01
3  Wheat                  5            100.000000           84.089101                  100.000000                 83.059185                    0.0         0.000000e+00

In [21]:
#Total tolerance analysis
total_tolerance_10 = (
    total_comparisons
    .groupby("crop")
    .agg(
        matched=("crop", "size"),
        
        area_within_10_pct=(
            "area_difference_pct",
            lambda x: (x <= 10).mean() * 100
        ),
        
        production_within_10_pct=(
            "production_difference_pct",
            lambda x: (x <= 10).mean() * 100
        ),
        
        yield_within_10_pct=(
            "yield_difference_pct",
            lambda x: (x <= 10).mean() * 100
        ),
        
        exact_yield_matches=(
            "yield_difference",
            lambda x: (x == 0).sum()
        )
    )
    .reset_index()
)

total_tolerance_10["exact_yield_match_pct"] = (
    total_tolerance_10["exact_yield_matches"]
    /
    total_tolerance_10["matched"]
    * 100
)

display(total_tolerance_10)

    crop  matched  area_within_10_pct  production_within_10_pct  yield_within_10_pct  exact_yield_matches  exact_yield_match_pct
0  Maize      393           62.595420                 77.099237           100.000000                  391              99.491094
1   Rice      363           94.214876                 98.071625            99.724518                  361              99.449036
2   Urad      338           43.491124                 36.686391            99.704142                  337              99.704142
3  Wheat        5            0.000000                  0.000000           100.000000                    5             100.000000

In [22]:
#Testing whether annual values are the sum of seasons
SEASONAL_COMPONENTS = [
    "Kharif",
    "Rabi",
    "Summer",
    "Autumn",
    "Winter"
]

seasonal_des = des_2022[
    des_2022["season"].isin(
        SEASONAL_COMPONENTS
    ) &
    des_2022["crop"].isin(
        VALIDATION_CROPS
    )
].copy()

In [23]:
#Aggregating seasonal values by district
seasonal_sum = (
    seasonal_des
    .groupby(
        [
            "state_code",
            "district_code",
            "crop"
        ]
    )
    .agg(
        seasonal_area_sum_ha=(
            "area_ha",
            "sum"
        ),
        
        seasonal_production_sum_tonnes=(
            "production_tonnes",
            "sum"
        )
    )
    .reset_index()
)

display(
    seasonal_sum.head()
)

   state_code  district_code   crop  seasonal_area_sum_ha  seasonal_production_sum_tonnes
0           1              2  Wheat                1071.0                       2035.1784
1           1              4  Wheat               15539.0                      34100.3444
2           1              5   Urad                 165.0                         45.7405
3           1              5  Wheat               81659.0                     208238.3007
4           1              7  Wheat               48315.0                      98802.4642

In [24]:
#Calculating annual yield from summed seasonal values
seasonal_sum["seasonal_yield_kg_ha"] = np.where(
    seasonal_sum["seasonal_area_sum_ha"] > 0,
    (
        seasonal_sum["seasonal_production_sum_tonnes"]
        * 1000
        /
        seasonal_sum["seasonal_area_sum_ha"]
    ),
    np.nan
)

display(
    seasonal_sum.head()
)

   state_code  district_code   crop  seasonal_area_sum_ha  seasonal_production_sum_tonnes  seasonal_yield_kg_ha
0           1              2  Wheat                1071.0                       2035.1784           1900.259944
1           1              4  Wheat               15539.0                      34100.3444           2194.500573
2           1              5   Urad                 165.0                         45.7405            277.215152
3           1              5  Wheat               81659.0                     208238.3007           2550.096140
4           1              7  Wheat               48315.0                      98802.4642           2044.964591

In [25]:
#Comparing seasonal sum with UPAG
seasonal_vs_upag = pd.merge(
    seasonal_sum,
    upag_2022[
        upag_2022["crop"].isin(
            VALIDATION_CROPS
        )
    ],
    on=[
        "state_code",
        "district_code",
        "crop"
    ],
    how="inner"
)

seasonal_vs_upag["area_difference_pct"] = (
    (
        seasonal_vs_upag["seasonal_area_sum_ha"]
        -
        seasonal_vs_upag["area_ha"]
    ).abs()
    /
    seasonal_vs_upag["seasonal_area_sum_ha"].abs()
    * 100
)

seasonal_vs_upag["production_difference_pct"] = (
    (
        seasonal_vs_upag["seasonal_production_sum_tonnes"]
        -
        seasonal_vs_upag["production_tonnes"]
    ).abs()
    /
    seasonal_vs_upag[
        "seasonal_production_sum_tonnes"
    ].abs()
    * 100
)

seasonal_vs_upag["yield_difference_pct"] = (
    (
        seasonal_vs_upag["seasonal_yield_kg_ha"]
        -
        seasonal_vs_upag["yield_kg_ha"]
    ).abs()
    /
    seasonal_vs_upag[
        "seasonal_yield_kg_ha"
    ].abs()
    * 100
)

display(
    seasonal_vs_upag.head()
)

,state_code,district_code,crop,seasonal_area_sum_ha,seasonal_production_sum_tonnes,seasonal_yield_kg_ha,state,district,census_code,crop_source_name,year,area_lakh_ha,area_ha,production_lakh_tonnes,production_tonnes,yield_kg_ha,yield_tonnes_ha,yield_quintal_acre,data_source,area_difference_pct,production_difference_pct,yield_difference_pct
0,1,2,Wheat,1071.0,2035.1784,1900.259944,Jammu And Kashmir,Budgam,2.0,Wheat,2022-2023,0.01,1000.0,0.02,2000.0,1900.0,1.900,7.689039,UPAg,6.629318,1.728517,0.013679
1,1,4,Wheat,15539.0,34100.3444,2194.500573,Jammu And Kashmir,Doda,16.0,Wheat,2022-2023,0.16,16000.0,0.34,34000.0,2195.0,2.195,8.882864,UPAg,2.966729,0.294262,0.022758
2,1,5,Urad,165.0,45.7405,277.215152,Jammu And Kashmir,Jammu,21.0,Urad,2022-2023,0.00,0.0,0.00,0.0,277.0,0.277,1.120981,UPAg,100.000000,100.000000,0.077612
3,1,5,Wheat,81659.0,208238.3007,2550.096140,Jammu And Kashmir,Jammu,21.0,Wheat,2022-2023,0.82,82000.0,2.08,208000.0,2550.0,2.550,10.319500,UPAg,0.417590,0.114437,0.003770
4,1,7,Wheat,48315.0,98802.4642,2044.964591,Jammu And Kashmir,Kathua,7.0,Wheat,2022-2023,0.48,48000.0,0.99,99000.0,2045.0,2.045,8.275834,UPAg,0.651971,0.199930,0.001732

In [26]:
#Summarizing season sum comparison
seasonal_sum_summary = (
    seasonal_vs_upag
    .groupby("crop")
    .agg(
        matched_districts=(
            "district_code",
            "nunique"
        ),
        
        median_area_diff_pct=(
            "area_difference_pct",
            "median"
        ),
        
        mean_area_diff_pct=(
            "area_difference_pct",
            "mean"
        ),
        
        median_production_diff_pct=(
            "production_difference_pct",
            "median"
        ),
        
        mean_production_diff_pct=(
            "production_difference_pct",
            "mean"
        ),
        
        median_yield_diff_pct=(
            "yield_difference_pct",
            "median"
        ),
        
        mean_yield_diff_pct=(
            "yield_difference_pct",
            "mean"
        )
    )
    .reset_index()
)

display(seasonal_sum_summary)

    crop  matched_districts  median_area_diff_pct  mean_area_diff_pct  median_production_diff_pct  mean_production_diff_pct  median_yield_diff_pct  mean_yield_diff_pct
0  Maize                650              7.024592           31.621331                    2.796192                 20.188441               0.006378             0.008143
1   Rice                675              0.412373            7.861210                    0.171285                  6.239108               0.007386             0.127209
2   Urad                581             20.918984           46.005276                   49.253731                 53.944527               0.034568             0.216662
3  Wheat                544              0.780443           26.115373                    0.249357                 23.274080               0.004593             0.007770

In [27]:
#Comparing all candidate representations
candidate_results = season_comparison_summary.copy()

candidate_results = candidate_results.rename(
    columns={
        "des_representation": "representation"
    }
)

candidate_results["method_type"] = "Individual season"

candidate_total = total_summary.copy()

candidate_total = candidate_total.rename(
    columns={
        "crop": "crop"
    }
)

candidate_total["representation"] = "Total"
candidate_total["method_type"] = "DES Total"

candidate_total = candidate_total[
    [
        "crop",
        "representation",
        "method_type",
        "matched_districts",
        "median_area_diff_pct",
        "mean_area_diff_pct",
        "median_production_diff_pct",
        "mean_production_diff_pct",
        "median_yield_diff_pct",
        "mean_yield_diff_pct"
    ]
]

candidate_season_sum = seasonal_sum_summary.copy()

candidate_season_sum["representation"] = (
    "Sum of Kharif+Rabi+Summer+Autumn+Winter"
)

candidate_season_sum["method_type"] = (
    "Seasonal aggregation"
)

candidate_season_sum = candidate_season_sum[
    [
        "crop",
        "representation",
        "method_type",
        "matched_districts",
        "median_area_diff_pct",
        "mean_area_diff_pct",
        "median_production_diff_pct",
        "mean_production_diff_pct",
        "median_yield_diff_pct",
        "mean_yield_diff_pct"
    ]
]

candidate_results = pd.concat(
    [
        candidate_results[
            [
                "crop",
                "representation",
                "method_type",
                "matched_districts",
                "median_area_diff_pct",
                "mean_area_diff_pct",
                "median_production_diff_pct",
                "mean_production_diff_pct",
                "median_yield_diff_pct",
                "mean_yield_diff_pct"
            ]
        ],
        candidate_total,
        candidate_season_sum
    ],
    ignore_index=True
)

display(
    candidate_results.sort_values(
        [
            "crop",
            "median_area_diff_pct"
        ]
    )
)

,crop,representation,method_type,matched_districts,median_area_diff_pct,mean_area_diff_pct,median_production_diff_pct,mean_production_diff_pct,median_yield_diff_pct,mean_yield_diff_pct
4,Maize,Total,Individual season,393,5.060410,24.511288,1.746725,13.328732,0.000000,8.520801e-17
24,Maize,Total,DES Total,393,5.060410,24.511288,1.746725,13.328732,0.000000,8.520801e-17
28,Maize,Sum of Kharif+Rabi+Summer+Autumn+Winter,Seasonal aggregation,650,7.024592,31.621331,2.796192,20.188441,0.006378,8.142579e-03
1,Maize,Kharif,Individual season,552,38.082444,5088.757143,28.354995,2701.436543,0.249004,8.821001e+00
0,Maize,Autumn,Individual season,74,100.000000,770.928719,292.884906,2026.510471,26.891859,5.398953e+01
5,Maize,Whole Year,Individual season,5,100.000000,100.000000,100.000000,100.000000,0.000000,0.000000e+00
6,Maize,Winter,Individual season,10,100.000000,4952.027650,2029.059402,6305.972059,10.838321,1.286528e+01
2,Maize,Rabi,Individual season,351,203.030303,20538.668156,188.184438,16673.149493,10.691469,1.797155e+01
3,Maize,Summer,Individual season,214,658.971407,5113.687624,714.627033,5361.115034,17.221027,3.096781e+01
11,Rice,Total,Individual season,363,0.321960,2.770906,0.106164,1.409153,0.000000,2.202852e-01
25,Rice,Total,DES Total,363,0.321960,2.770906,0.106164,1.409153,0.000000,2.202852e-01
29,Rice,Sum of Kharif+Rabi+Summer+Autumn+Winter,Seasonal aggregation,675,0.412373,7.861210,0.171285,6.239108,0.007386,1.272087e-01
8,Rice,Kharif,Individual season,485,2.540731,111.758602,1.729400,272.771631,0.000000,6.703368e+00
12,Rice,Winter,Individual season,193,28.886741,51.642490,29.470126,52.526205,2.045944,3.963866e+00
9,Rice,Rabi,Individual season,115,141.637276,15456.069720,152.684776,14130.497835,5.395683,1.566896e+01
7,Rice,Autumn,Individual season,176,952.444271,17319.558652,1402.588911,27585.976536,20.351094,3.641408e+01
10,Rice,Summer,Individual season,246,1427.514055,106243.859744,1325.379785,70703.280180,12.066830,1.590733e+01
17,Urad,Total,Individual season,338,14.857075,40.060564,26.700305,48.627406,0.000000,2.958580e-01
26,Urad,Total,DES Total,338,14.857075,40.060564,26.700305,48.627406,0.000000,2.958580e-01
30,Urad,Sum of Kharif+Rabi+Summer+Autumn+Winter,Seasonal aggregation,581,20.918984,46.005276,49.253731,53.944527,0.034568,2.166621e-01
18,Urad,Winter,Individual season,28,79.554495,2068.514049,100.000000,1962.161417,1.418378,7.258302e+00
14,Urad,Kharif,Individual season,488,90.181512,1014.720453,100.000000,559.021099,0.452489,1.981426e+01
13,Urad,Autumn,Individual season,15,100.000000,22898.217625,100.000000,17338.481662,3.030303,1.180444e+01
15,Urad,Rabi,Individual season,239,100.000000,7456.805275,100.000000,4818.775509,4.171240,1.232544e+01
16,Urad,Summer,Individual season,161,900.000000,91495.091682,350.450450,69665.162661,24.944072,2.887493e+01
20,Wheat,Rabi,Individual season,537,0.749780,25.149742,0.239218,22.277536,0.000000,2.693632e-04
31,Wheat,Sum of Kharif+Rabi+Summer+Autumn+Winter,Seasonal aggregation,544,0.780443,26.115373,0.249357,23.274080,0.004593,7.770398e-03
19,Wheat,Kharif,Individual season,5,100.000000,1012.380952,100.000000,1455.348837,1.074219,1.634844e+00
21,Wheat,Summer,Individual season,7,100.000000,100.000000,100.000000,100.000000,0.000000,0.000000e+00
22,Wheat,Total,Individual season,5,100.000000,84.089101,100.000000,83.059185,0.000000,0.000000e+00
23,Wheat,Whole Year,Individual season,9,100.000000,100.000000,42.857143,50.184244,0.000000,0.000000e+00
27,Wheat,Total,DES Total,5,100.000000,84.089101,100.000000,83.059185,0.000000,0.000000e+00

In [28]:
#Automatically identifying best representation
ranking = candidate_results.copy()

ranking["combined_median_score"] = (
    ranking["median_area_diff_pct"]
    +
    ranking["median_production_diff_pct"]
    +
    ranking["median_yield_diff_pct"]
)

ranking = ranking.sort_values(
    [
        "crop",
        "combined_median_score"
    ]
)

display(
    ranking[
        [
            "crop",
            "representation",
            "method_type",
            "matched_districts",
            "median_area_diff_pct",
            "median_production_diff_pct",
            "median_yield_diff_pct",
            "combined_median_score"
        ]
    ]
)

     crop                           representation           method_type  matched_districts  median_area_diff_pct  median_production_diff_pct  median_yield_diff_pct  combined_median_score
4   Maize                                    Total     Individual season                393              5.060410                    1.746725               0.000000               6.807135
24  Maize                                    Total             DES Total                393              5.060410                    1.746725               0.000000               6.807135
28  Maize  Sum of Kharif+Rabi+Summer+Autumn+Winter  Seasonal aggregation                650              7.024592                    2.796192               0.006378               9.827162
1   Maize                                   Kharif     Individual season                552             38.082444                   28.354995               0.249004              66.686443
5   Maize                               Whole Year     Individual season                  5            100.000000                  100.000000               0.000000             200.000000
2   Maize                                     Rabi     Individual season                351            203.030303                  188.184438              10.691469             401.906210
0   Maize                                   Autumn     Individual season                 74            100.000000                  292.884906              26.891859             419.776765
3   Maize                                   Summer     Individual season                214            658.971407                  714.627033              17.221027            1390.819467
6   Maize                                   Winter     Individual season                 10            100.000000                 2029.059402              10.838321            2139.897723
11   Rice                                    Total     Individual season                363              0.321960                    0.106164               0.000000               0.428124
25   Rice                                    Total             DES Total                363              0.321960                    0.106164               0.000000               0.428124
29   Rice  Sum of Kharif+Rabi+Summer+Autumn+Winter  Seasonal aggregation                675              0.412373                    0.171285               0.007386               0.591045
8    Rice                                   Kharif     Individual season                485              2.540731                    1.729400               0.000000               4.270131
12   Rice                                   Winter     Individual season                193             28.886741                   29.470126               2.045944              60.402811
9    Rice                                     Rabi     Individual season                115            141.637276                  152.684776               5.395683             299.717735
7    Rice                                   Autumn     Individual season                176            952.444271                 1402.588911              20.351094            2375.384276
10   Rice                                   Summer     Individual season                246           1427.514055                 1325.379785              12.066830            2764.960671
17   Urad                                    Total     Individual season                338             14.857075                   26.700305               0.000000              41.557380
26   Urad                                    Total             DES Total                338             14.857075                   26.700305               0.000000              41.557380
30   Urad  Sum of Kharif+Rabi+Summer+Autumn+Winter  Seasonal aggregation                581             20.918984                   49.253731               0.034568              70.207284
18   Urad                                   Winter     Individual season                 28             79.554495                  100.000000               1.418378             180.972873
14   Urad                                   Kharif     Individual season                488             90.181512                  100.000000               0.452489             190.634000
13   Urad                                   Autumn     Individual season                 15            100.000000                  100.000000               3.030303             203.030303
15   Urad                                     Rabi     Individual season                239            100.000000                  100.000000               4.171240             204.171240
16   Urad                                   Summer     Individual season                161            900.000000                  350.450450              24.944072            1275.394522
20  Wheat                                     Rabi     Individual season                537              0.749780                    0.239218               0.000000               0.988998
31  Wheat  Sum of Kharif+Rabi+Summer+Autumn+Winter  Seasonal aggregation                544              0.780443                    0.249357               0.004593               1.034393
23  Wheat                               Whole Year     Individual season                  9            100.000000                   42.857143               0.000000             142.857143
21  Wheat                                   Summer     Individual season                  7            100.000000                  100.000000               0.000000             200.000000
22  Wheat                                    Total     Individual season                  5            100.000000                  100.000000               0.000000             200.000000
27  Wheat                                    Total             DES Total                  5            100.000000                  100.000000               0.000000             200.000000
19  Wheat                                   Kharif     Individual season                  5            100.000000                  100.000000               1.074219             201.074219

In [29]:
#Getting best candidate per crop
best_candidates = (
    ranking
    .groupby("crop")
    .head(1)
    .reset_index(drop=True)
)

display(best_candidates)

,crop,representation,method_type,matched_districts,median_area_diff_pct,mean_area_diff_pct,median_production_diff_pct,mean_production_diff_pct,median_yield_diff_pct,mean_yield_diff_pct,combined_median_score
0,Maize,Total,Individual season,393,5.060410,24.511288,1.746725,13.328732,0.0,8.520801e-17,6.807135
1,Rice,Total,Individual season,363,0.321960,2.770906,0.106164,1.409153,0.0,2.202852e-01,0.428124
2,Urad,Total,Individual season,338,14.857075,40.060564,26.700305,48.627406,0.0,2.958580e-01,41.557380
3,Wheat,Rabi,Individual season,537,0.749780,25.149742,0.239218,22.277536,0.0,2.693632e-04,0.988998

In [ ]:
#Inspecting worst mismatches for each representation
for crop in VALIDATION_CROPS:
    
    print(f"WORST MATCHES — {crop}")
    
    crop_data = season_comparisons[
        season_comparisons["crop"] == crop
    ].copy()
    
    for representation in crop_data[
        "des_representation"
    ].unique():
        
        temp = crop_data[
            crop_data["des_representation"]
            == representation
        ].copy()
        
        if temp.empty:
            continue
        
        print(
            f"\n--- {representation} ---"
        )
        
        display(
            temp[
                [
                    "state_des",
                    "district_des",
                    "area_ha_des",
                    "area_ha_upag",
                    "area_difference_pct",
                    "production_tonnes_des",
                    "production_tonnes_upag",
                    "production_difference_pct",
                    "yield_kg_ha_des",
                    "yield_kg_ha_upag",
                    "yield_difference_pct"
                ]
            ]
            .sort_values(
                "area_difference_pct",
                ascending=False
            )
            .head(5)
        )

====================================================================================================
WORST MATCHES — Rice
====================================================================================================

--- Autumn ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
101,Odisha,Khordha,10.0,82000.0,819900.000000,20.0,244000.0,1.219900e+06,2000.0,2967.0,48.350000
45,Bihar,Patna,12.0,65000.0,541566.666667,23.0,210000.0,9.129435e+05,1917.0,3240.0,69.014085
8,Assam,Charaideo,15.0,35000.0,233233.333333,23.0,88000.0,3.825087e+05,1533.0,2540.0,65.688193
12,Assam,Dhubri,40.0,78000.0,194900.000000,62.0,244000.0,3.934484e+05,1550.0,3103.0,100.193548
173,West Bengal,Purulia,153.0,249000.0,162645.098039,414.0,593000.0,1.431367e+05,2706.0,2381.0,12.010347

--- Kharif ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
572,Tripura,West Tripura,176.0,23000.0,12968.181818,192.0,80000.0,41566.666667,1091.0,3437.0,215.032081
569,Tripura,Sepahijala,417.0,46000.0,10931.175060,427.0,159000.0,37136.533958,1024.0,3480.0,239.843750
570,Tripura,South Tripura,954.0,39000.0,3988.050314,998.0,132000.0,13126.452906,1046.0,3381.0,223.231358
566,Tripura,Gomati,1771.0,38000.0,2045.680407,1863.0,126000.0,6663.285024,1052.0,3340.0,217.490494
567,Tripura,Khowai,1224.0,23000.0,1779.084967,1404.0,74000.0,5170.655271,1147.0,3197.0,178.727114

--- Rabi ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
728,Karnataka,Kodagu,1.0,13000.0,1.299900e+06,3.0,34000.0,1.133233e+06,3000.0,2571.0,14.300000
733,Karnataka,Shivamogga,92.0,81000.0,8.794348e+04,245.0,208000.0,8.479796e+04,2663.0,2578.0,3.191889
731,Karnataka,Mandya,95.0,75000.0,7.884737e+04,223.0,225000.0,1.007969e+05,2347.0,2995.0,27.609715
723,Karnataka,Dharwad,15.0,9000.0,5.990000e+04,39.0,13000.0,3.323333e+04,2600.0,1465.0,43.653846
714,Karnataka,Belagavi,97.0,52000.0,5.350825e+04,258.0,144000.0,5.571395e+04,2660.0,2759.0,3.721805

--- Summer ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
980,Uttar Pradesh,Hardoi,2.0,148000.0,7.399900e+06,0.0,395000.0,NaN,0.0,2677.0,NaN
809,Bihar,Darbhanga,3.0,96000.0,3.199900e+06,6.0,182000.0,3.033233e+06,2000.0,1889.0,5.550000
982,Uttar Pradesh,Jaunpur,6.0,146000.0,2.433233e+06,21.0,412000.0,1.961805e+06,3500.0,2815.0,19.571429
978,Uttar Pradesh,Ghazipur,8.0,150000.0,1.874900e+06,28.0,504000.0,1.799900e+06,3500.0,3358.0,4.057143
970,Uttar Pradesh,Bara Banki,18.0,189000.0,1.049900e+06,62.0,461000.0,7.434484e+05,3444.0,2444.0,29.036005

--- Total ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
1255,Tamil Nadu,Chennai,121.000,0.0,100.000000,356.00,0.0,100.000000,2942.0,2942.0,0.0
1148,Karnataka,Bengaluru Rural,191.000,0.0,100.000000,578.00,1000.0,73.010381,3026.0,3026.0,0.0
1176,Kerala,Idukki,362.438,0.0,100.000000,925.39,1000.0,8.062547,2553.0,2553.0,0.0
1172,Karnataka,Vijayapura,105.000,0.0,100.000000,330.00,0.0,100.000000,3143.0,3143.0,0.0
1153,Karnataka,Chitradurga,720.000,1000.0,38.888889,1229.00,1000.0,18.633035,1707.0,1707.0,0.0

--- Winter ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
1456,Kerala,Alappuzha,6288.49,39000.0,520.180679,19462.75,120000.0,516.562408,3095.0,3088.0,0.226171
1466,Kerala,Pathanamthitta,729.34,4000.0,448.441056,2001.87,12000.0,499.439524,2745.0,3308.0,20.510018
1539,Tamil Nadu,Thoothukkudi,2404.00,13000.0,440.765391,9267.00,53000.0,471.921873,3855.0,4145.0,7.522698
1462,Kerala,Kottayam,4472.40,18000.0,302.468473,14453.72,56000.0,287.443509,3232.0,3098.0,4.146040
1512,Tamil Nadu,Chengalpattu,14719.00,57000.0,287.254569,60162.00,241000.0,300.585087,4087.0,4212.0,3.058478

====================================================================================================
WORST MATCHES — Wheat
====================================================================================================

--- Kharif ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
1578,Telangana,Adilabad,21.0,1000.0,4661.904762,43.0,3000.0,6876.744186,2048.0,2070.0,1.074219
1579,Telangana,Jangoan,2.0,0.0,100.000000,4.0,0.0,100.000000,2000.0,2000.0,0.000000
1580,Telangana,Nagarkurnool,1.0,0.0,100.000000,2.0,0.0,100.000000,2000.0,2000.0,0.000000
1581,Telangana,Sangareddy,1.0,0.0,100.000000,2.0,0.0,100.000000,2000.0,2071.0,3.550000
1582,Telangana,Vikarabad,1.0,0.0,100.000000,2.0,0.0,100.000000,2000.0,2071.0,3.550000

--- Rabi ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
2118,West Bengal,South 24 Parganas,315.0,0.0,100.0,1036.0,1000.0,3.474903,3289.0,3289.0,0.0
1583,Andhra Pradesh,Ananthapuramu,10.0,0.0,100.0,10.0,0.0,100.000000,1000.0,1000.0,0.0
1584,Andhra Pradesh,Kurnool,20.0,0.0,100.0,27.0,0.0,100.000000,1350.0,1350.0,0.0
1585,Andhra Pradesh,Palnadu,5.0,0.0,100.0,6.0,0.0,100.000000,1200.0,1200.0,0.0
1586,Andhra Pradesh,Y.S.R. Kadapa,24.0,0.0,100.0,29.0,0.0,100.000000,1208.0,1208.0,0.0

--- Summer ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
2120,Odisha,Bargarh,82.0,0.0,100.0,130.9,0.0,100.0,1596.0,1596.0,0.0
2121,Odisha,Bhadrak,2.0,0.0,100.0,1.8,0.0,100.0,900.0,900.0,0.0
2122,Odisha,Dhenkanal,1.0,0.0,100.0,1.2,0.0,100.0,1200.0,1200.0,0.0
2123,Odisha,Jajpur,1.0,0.0,100.0,0.8,0.0,100.0,800.0,800.0,0.0
2124,Odisha,Mayurbhanj,24.0,0.0,100.0,36.6,0.0,100.0,1525.0,1525.0,0.0

--- Total ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
2128,Telangana,Jangoan,3.0,0.0,100.000000,6.0,0.0,100.000000,2000.0,2000.0,0.0
2130,Telangana,Sangareddy,169.0,0.0,100.000000,350.0,0.0,100.000000,2071.0,2071.0,0.0
2129,Telangana,Nagarkurnool,3.0,0.0,100.000000,6.0,0.0,100.000000,2000.0,2000.0,0.0
2131,Telangana,Vikarabad,28.0,0.0,100.000000,58.0,0.0,100.000000,2071.0,2071.0,0.0
2127,Telangana,Adilabad,1257.0,1000.0,20.445505,2602.0,3000.0,15.295926,2070.0,2070.0,0.0

--- Whole Year ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
2132,Manipur,Bishnupur,500.0,1000.0,100.0,1250.0,1000.0,20.000000,2500.0,2500.0,0.0
2133,Manipur,Chandel,20.0,0.0,100.0,40.0,0.0,100.000000,2000.0,2000.0,0.0
2134,Manipur,Churachandpur,460.0,0.0,100.0,1150.0,1000.0,13.043478,2500.0,2500.0,0.0
2135,Manipur,Imphal East,260.0,0.0,100.0,600.0,1000.0,66.666667,2308.0,2308.0,0.0
2136,Manipur,Imphal West,260.0,0.0,100.0,700.0,1000.0,42.857143,2692.0,2692.0,0.0

====================================================================================================
WORST MATCHES — Maize
====================================================================================================

--- Autumn ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
2198,West Bengal,Dakshin Dinajpur,23.0,5000.0,21639.130435,100.0,58000.0,57900.000000,4348.0,12485.0,187.143514
2164,Bihar,Purnia,393.0,50000.0,12622.646310,1499.0,463000.0,30787.258172,3814.0,9322.0,144.415312
2155,Bihar,Madhepura,1235.0,33000.0,2572.064777,7079.0,251000.0,3445.698545,5732.0,7687.0,34.106769
2168,Bihar,Sheohar,42.0,1000.0,2280.952381,137.0,8000.0,5739.416058,3262.0,5684.0,74.248927
2152,Bihar,Katihar,3629.0,81000.0,2132.019840,15375.0,782000.0,4986.178862,4237.0,9697.0,128.864763

--- Kharif ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
2632,Tamil Nadu,Thoothukkudi,2.0,50000.0,2.499900e+06,19.0,177000.0,931478.947368,9500.0,3531.0,62.831579
2221,Andhra Pradesh,Dr. B.R. Ambedkar Konaseema,1.0,1000.0,9.990000e+04,4.0,11000.0,274900.000000,4000.0,9568.0,139.200000
2487,Maharashtra,Gondia,3.0,2000.0,6.656667e+04,9.0,4000.0,44344.444444,3000.0,1743.0,41.900000
2224,Andhra Pradesh,Guntur,109.0,26000.0,2.375321e+04,455.0,324000.0,71108.791209,4174.0,12491.0,199.257307
2626,Tamil Nadu,Tenkasi,128.0,17000.0,1.318125e+04,1003.0,78000.0,7676.669990,7836.0,4720.0,39.765186

--- Rabi ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
3053,Uttar Pradesh,Aligarh,1.0,23000.0,2.299900e+06,3.0,57000.0,1.899900e+06,3000.0,2467.0,17.766667
3096,Uttar Pradesh,Sitapur,1.0,14000.0,1.399900e+06,3.0,15000.0,4.999000e+05,3000.0,1138.0,62.066667
3079,Uttar Pradesh,Kasganj,3.0,42000.0,1.399900e+06,8.0,124000.0,1.549900e+06,2667.0,2925.0,9.673791
3069,Uttar Pradesh,Farrukhabad,17.0,39000.0,2.293118e+05,48.0,115000.0,2.394833e+05,2824.0,2949.0,4.426346
3077,Uttar Pradesh,Kanpur Dehat,7.0,15000.0,2.141857e+05,20.0,43000.0,2.149000e+05,2857.0,2838.0,0.665033

--- Summer ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
3309,Uttarakhand,Nainital,1.0,2000.0,199900.000000,3.0,7000.0,233233.333333,3000.0,2976.0,0.800000
3170,Karnataka,Bengaluru Urban,1.0,1000.0,99900.000000,4.0,4000.0,99900.000000,4000.0,5382.0,34.550000
3306,Uttar Pradesh,Varanasi,5.0,4000.0,79900.000000,14.0,10000.0,71328.571429,2800.0,2653.0,5.250000
3232,Odisha,Gajapati,20.0,15000.0,74900.000000,22.9,35000.0,152738.427948,1145.0,2274.0,98.602620
3278,Uttar Pradesh,Jaunpur,119.0,54000.0,45278.151261,342.0,144000.0,42005.263158,2874.0,2653.0,7.689631

--- Total ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
3723,West Bengal,South 24 Parganas,245.0,0.0,100.0,2024.0,2000.0,1.185771,8261.0,8261.0,0.0
3721,West Bengal,Purba Bardhaman,96.0,0.0,100.0,564.0,1000.0,77.304965,5875.0,5875.0,0.0
3333,Andhra Pradesh,Anakapalli,90.0,0.0,100.0,688.0,1000.0,45.348837,7644.0,7644.0,0.0
3702,Uttarakhand,Haridwar,135.0,0.0,100.0,501.0,1000.0,99.600798,3711.0,3711.0,0.0
3688,Uttar Pradesh,Rampur,295.0,0.0,100.0,842.0,1000.0,18.764846,2854.0,2854.0,0.0

--- Whole Year ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
3725,Kerala,Alappuzha,9.14,0.0,100.0,2.74,0.0,100.0,300.0,300.0,0.0
3726,Kerala,Idukki,5.88,0.0,100.0,12.21,0.0,100.0,2077.0,2077.0,0.0
3727,Kerala,Kannur,0.20,0.0,100.0,0.32,0.0,100.0,1600.0,1600.0,0.0
3728,Kerala,Palakkad,72.47,0.0,100.0,241.88,0.0,100.0,3338.0,3338.0,0.0
3729,Kerala,Wayanad,0.51,0.0,100.0,1.52,0.0,100.0,2980.0,2980.0,0.0

--- Winter ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
3736,Odisha,Keonjhar,5.0,1000.0,19900.000000,11.1,4000.0,35936.036036,2220.0,2738.0,23.333333
3735,Odisha,Kandhamal,8.0,1000.0,12400.000000,12.4,1000.0,7964.516129,1550.0,1429.0,7.806452
3739,Odisha,Rayagada,31.0,3000.0,9577.419355,46.3,4000.0,8539.308855,1494.0,1733.0,15.997323
3731,Odisha,Balangir,42.0,3000.0,7042.857143,159.7,10000.0,6161.740764,3802.0,3643.0,4.182009
3730,Odisha,Angul,11.0,0.0,100.000000,29.1,1000.0,3336.426117,2645.0,2532.0,4.272212

====================================================================================================
WORST MATCHES — Urad
====================================================================================================

--- Autumn ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
3752,Odisha,Rayagada,2.0,4000.0,199900.000000,0.5,1000.0,199900.000000,250.0,279.0,11.600000
3748,Odisha,Kandhamal,1.0,1000.0,99900.000000,0.4,0.0,100.000000,400.0,504.0,26.000000
3745,Odisha,Dhenkanal,6.0,2000.0,33233.333333,2.0,1000.0,49900.000000,333.0,432.0,29.729730
3747,Odisha,Ganjam,174.0,12000.0,6796.551724,32.7,3000.0,9074.311927,188.0,230.0,22.340426
3746,Odisha,Gajapati,67.0,2000.0,2885.074627,17.7,0.0,100.000000,264.0,272.0,3.030303

--- Kharif ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
4076,Tamil Nadu,Mayiladuthurai,12.0,24000.0,199900.000000,10.0,5000.0,49900.000000,833.0,219.0,73.709484
3775,Andhra Pradesh,Srikakulam,30.0,21000.0,69900.000000,32.0,15000.0,46775.000000,1067.0,735.0,31.115276
3761,Andhra Pradesh,Dr. B.R. Ambedkar Konaseema,2.0,1000.0,49900.000000,2.0,0.0,100.000000,1000.0,242.0,75.800000
4083,Tamil Nadu,Tenkasi,116.0,28000.0,24037.931034,99.0,11000.0,11011.111111,853.0,400.0,53.106682
4113,Telangana,Nagarkurnool,36.0,6000.0,16566.666667,47.0,7000.0,14793.617021,1306.0,1281.0,1.914242

--- Rabi ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
4360,Karnataka,Bidar,1.0,8000.0,799900.000000,1.0,5000.0,499900.0,1000.0,564.0,43.60000
4368,Karnataka,Kalaburagi,7.0,22000.0,314185.714286,4.0,13000.0,324900.0,571.0,608.0,6.47986
4371,Karnataka,Mysuru,3.0,8000.0,266566.666667,2.0,2000.0,99900.0,667.0,264.0,60.41979
4458,Telangana,Vikarabad,5.0,4000.0,79900.000000,8.0,2000.0,24900.0,1600.0,474.0,70.37500
4377,Karnataka,Vijayapura,2.0,1000.0,49900.000000,1.0,0.0,100.0,500.0,382.0,23.60000

--- Summer ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
4511,Madhya Pradesh,Datia,1.0,32000.0,3.199900e+06,1.000,10000.0,9.999000e+05,1000.0,330.0,67.000000
4543,Maharashtra,Dharashiv,2.0,41000.0,2.049900e+06,1.056,26000.0,2.462021e+06,528.0,629.0,19.128788
4539,Madhya Pradesh,Vidisha,3.0,55000.0,1.833233e+06,3.000,33000.0,1.099900e+06,1000.0,605.0,39.500000
4500,Madhya Pradesh,Alirajpur,3.0,29000.0,9.665667e+05,2.000,15000.0,7.499000e+05,667.0,510.0,23.538231
4537,Madhya Pradesh,Tikamgarh,17.0,159000.0,9.351941e+05,9.000,84000.0,9.332333e+05,529.0,530.0,0.189036

--- Total ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
4962,Uttar Pradesh,Siddharthnagar,344.0,0.0,100.0,184.0,0.0,100.0,535.0,535.0,0.0
4671,Arunachal Pradesh,Dibang Valley,69.0,0.0,100.0,48.0,0.0,100.0,696.0,696.0,0.0
4672,Arunachal Pradesh,East Kameng,161.0,0.0,100.0,135.0,0.0,100.0,839.0,839.0,0.0
4674,Arunachal Pradesh,Kamle,55.0,0.0,100.0,59.0,0.0,100.0,1073.0,1073.0,0.0
4673,Arunachal Pradesh,East Siang,157.0,0.0,100.0,161.0,0.0,100.0,1025.0,1025.0,0.0

--- Winter ---

,state_des,district_des,area_ha_des,area_ha_upag,area_difference_pct,production_tonnes_des,production_tonnes_upag,production_difference_pct,yield_kg_ha_des,yield_kg_ha_upag,yield_difference_pct
4983,Odisha,Bargarh,4.0,2000.0,49900.000000,2.1,1000.0,47519.047619,525.0,342.0,34.857143
5003,Odisha,Nuapada,147.0,4000.0,2621.088435,23.2,1000.0,4210.344828,158.0,168.0,6.329114
4997,Odisha,Khordha,43.0,1000.0,2225.581395,11.9,0.0,100.000000,277.0,446.0,61.010830
5008,Odisha,Sundargarh,113.0,1000.0,784.955752,34.0,0.0,100.000000,301.0,391.0,29.900332
4996,Odisha,Keonjhar,270.0,2000.0,640.740741,103.4,1000.0,867.117988,383.0,397.0,3.655352

In [31]:
#Specifically investigating the four original examples
example_results = []

for crop, state, district in EXAMPLES:
    
    # DES rows
    d = des_2022[
        (des_2022["crop"] == crop) &
        (des_2022["state"] == state) &
        (des_2022["district"] == district)
    ].copy()
    
    # UPAg row
    u = upag_2022[
        (upag_2022["crop"] == crop) &
        (upag_2022["state"] == state) &
        (upag_2022["district"] == district)
    ].copy()
    
    if u.empty:
        continue
    
    u_row = u.iloc[0]
    
    for _, d_row in d.iterrows():
        
        example_results.append({
            "crop": crop,
            "state": state,
            "district": district,
            "des_season": d_row["season"],
            
            "des_area_ha": d_row["area_ha"],
            "upag_area_ha": u_row["area_ha"],
            
            "des_production_tonnes":
                d_row["production_tonnes"],
            "upag_production_tonnes":
                u_row["production_tonnes"],
            
            "des_yield_kg_ha":
                d_row["yield_kg_ha"],
            "upag_yield_kg_ha":
                u_row["yield_kg_ha"]
        })

example_results = pd.DataFrame(
    example_results
)

example_results["area_diff_pct"] = (
    (
        example_results["des_area_ha"]
        -
        example_results["upag_area_ha"]
    ).abs()
    /
    example_results["des_area_ha"].abs()
    * 100
)

example_results["production_diff_pct"] = (
    (
        example_results["des_production_tonnes"]
        -
        example_results["upag_production_tonnes"]
    ).abs()
    /
    example_results["des_production_tonnes"].abs()
    * 100
)

example_results["yield_diff_pct"] = (
    (
        example_results["des_yield_kg_ha"]
        -
        example_results["upag_yield_kg_ha"]
    ).abs()
    /
    example_results["des_yield_kg_ha"].abs()
    * 100
)

display(
    example_results.sort_values(
        ["crop", "area_diff_pct"]
    )
)

,crop,state,district,des_season,des_area_ha,upag_area_ha,des_production_tonnes,upag_production_tonnes,des_yield_kg_ha,upag_yield_kg_ha,area_diff_pct,production_diff_pct,yield_diff_pct
1,Maize,Tamil Nadu,Thoothukkudi,Rabi,50003.0,50000.0,176557.0000,177000.0,3531.0,3531.0,5.999640e-03,0.250910,0.000000
2,Maize,Tamil Nadu,Thoothukkudi,Total,50005.0,50000.0,176576.0000,177000.0,3531.0,3531.0,9.999000e-03,0.240123,0.000000
0,Maize,Tamil Nadu,Thoothukkudi,Kharif,2.0,50000.0,19.0000,177000.0,9500.0,3531.0,2.499900e+06,931478.947368,62.831579
6,Rice,Tripura,West Tripura,Total,23196.0,23000.0,79725.0000,80000.0,3437.0,3437.0,8.449733e-01,0.344936,0.000000
7,Rice,Tripura,West Tripura,Winter,14986.0,23000.0,51395.0000,80000.0,3430.0,3437.0,5.347658e+01,55.657165,0.204082
5,Rice,Tripura,West Tripura,Summer,7996.0,23000.0,28036.0000,80000.0,3506.0,3437.0,1.876438e+02,185.347410,1.968055
4,Rice,Tripura,West Tripura,Kharif,176.0,23000.0,192.0000,80000.0,1091.0,3437.0,1.296818e+04,41566.666667,215.032081
3,Rice,Tripura,West Tripura,Autumn,38.0,23000.0,102.0000,80000.0,2684.0,3437.0,6.042632e+04,78331.372549,28.055142
9,Urad,Tamil Nadu,Mayiladuthurai,Rabi,24304.0,24000.0,5309.0000,5000.0,218.0,219.0,1.250823e+00,5.820305,0.458716
10,Urad,Tamil Nadu,Mayiladuthurai,Total,24316.0,24000.0,5319.0000,5000.0,219.0,219.0,1.299556e+00,5.997368,0.000000
8,Urad,Tamil Nadu,Mayiladuthurai,Kharif,12.0,24000.0,10.0000,5000.0,833.0,219.0,1.999000e+05,49900.000000,73.709484
11,Wheat,Jammu And Kashmir,Budgam,Rabi,1071.0,1000.0,2035.1784,2000.0,1900.0,1900.0,6.629318e+00,1.728517,0.000000

In [32]:
#Checking whether DES Total is actually an annual aggregate
des_total = des_2022[
    (
        des_2022["season"]
        .astype(str)
        .str.strip()
        .str.lower()
        == "total"
    ) &
    des_2022["crop"].isin(VALIDATION_CROPS)
].copy()

seasonal_components = des_2022[
    des_2022["season"].isin(
        SEASONAL_COMPONENTS
    ) &
    des_2022["crop"].isin(
        VALIDATION_CROPS
    )
].copy()

seasonal_aggregate = (
    seasonal_components
    .groupby(
        [
            "state_code",
            "district_code",
            "crop"
        ]
    )
    .agg(
        seasonal_area=(
            "area_ha",
            "sum"
        ),
        seasonal_production=(
            "production_tonnes",
            "sum"
        )
    )
    .reset_index()
)

In [33]:
#Merging total with seasonal sum
total_vs_seasons = pd.merge(
    des_total[
        [
            "state_code",
            "district_code",
            "crop",
            "area_ha",
            "production_tonnes"
        ]
    ],
    seasonal_aggregate,
    on=[
        "state_code",
        "district_code",
        "crop"
    ],
    how="inner"
)

total_vs_seasons["area_difference_pct"] = (
    (
        total_vs_seasons["area_ha"]
        -
        total_vs_seasons["seasonal_area"]
    ).abs()
    /
    total_vs_seasons["area_ha"].abs()
    * 100
)

total_vs_seasons["production_difference_pct"] = (
    (
        total_vs_seasons["production_tonnes"]
        -
        total_vs_seasons["seasonal_production"]
    ).abs()
    /
    total_vs_seasons[
        "production_tonnes"
    ].abs()
    * 100
)

display(
    total_vs_seasons.head(20)
)

    state_code  district_code   crop   area_ha  production_tonnes  seasonal_area  seasonal_production  area_difference_pct  production_difference_pct
0           28            745  Maize    5644.0            19517.0         5644.0              19517.0                  0.0                        0.0
1           28            745   Rice   58705.0           175374.0        58705.0             175374.0                  0.0                        0.0
2           28            745   Urad    3023.0             2502.0         3023.0               2502.0                  0.0                        0.0
3           28            744  Maize      90.0              688.0           90.0                688.0                  0.0                        0.0
4           28            744   Rice   59406.0           186481.0        59406.0             186481.0                  0.0                        0.0
5           28            744   Urad    8857.0             4975.0         8857.0               4975.0                  0.0                        0.0
6           28            502  Maize   27586.0           161542.0        27586.0             161542.0                  0.0                        0.0
7           28            502   Rice   26995.0           103988.0        26995.0             103988.0                  0.0                        0.0
8           28            502   Urad     901.0             1105.0          901.0               1105.0                  0.0                        0.0
9           28            753  Maize    3262.0            19707.0         3262.0              19707.0                  0.0                        0.0
10          28            753   Rice   15906.0            52418.0        15906.0              52418.0                  0.0                        0.0
11          28            753   Urad     241.0              293.0          241.0                293.0                  0.0                        0.0
12          28            750  Maize   41450.0           473521.0        41450.0             473521.0                  0.0                        0.0
13          28            750   Rice  115379.0           480939.0       115379.0             480939.0                  0.0                        0.0
14          28            750   Urad   23972.0            36430.0        23972.0              36430.0                  0.0                        0.0
15          28            503  Maize    1194.0             7452.0         1194.0               7452.0                  0.0                        0.0
16          28            503   Rice   19888.0            62697.0        19888.0              62697.0                  0.0                        0.0
17          28            503   Urad     805.0              675.0          805.0                675.0                  0.0                        0.0
18          28            747  Maize    1154.0            11042.0         1154.0              11042.0                  0.0                        0.0
19          28            747   Rice  126790.0           584636.0       126790.0             584636.0                  0.0                        0.0

In [34]:
#Summarized total v/s seasonal sum
total_vs_seasons_summary = (
    total_vs_seasons
    .groupby("crop")
    .agg(
        matched_districts=(
            "district_code",
            "nunique"
        ),
        
        median_area_difference_pct=(
            "area_difference_pct",
            "median"
        ),
        
        mean_area_difference_pct=(
            "area_difference_pct",
            "mean"
        ),
        
        median_production_difference_pct=(
            "production_difference_pct",
            "median"
        ),
        
        mean_production_difference_pct=(
            "production_difference_pct",
            "mean"
        )
    )
    .reset_index()
)

display(total_vs_seasons_summary)

    crop  matched_districts  median_area_difference_pct  mean_area_difference_pct  median_production_difference_pct  mean_production_difference_pct
0  Maize                393                         0.0              1.193580e-16                               0.0                    2.723992e-16
1   Rice                363                         0.0              2.832467e-16                               0.0                    1.904267e-16
2   Urad                338                         0.0              1.013212e-03                               0.0                    1.013212e-03
3  Wheat                  5                         0.0              0.000000e+00                               0.0                    0.000000e+00

In [35]:
#Exporting all investigation results
OUTPUT_DIR = Path(
    "../data/processed/validation"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

season_distribution.to_csv(
    OUTPUT_DIR / "des_season_distribution_2022_23.csv",
    index=False
)

season_comparison_summary.to_csv(
    OUTPUT_DIR / "des_season_comparison_summary.csv",
    index=False
)

tolerance_10.to_csv(
    OUTPUT_DIR / "des_season_tolerance_10pct.csv",
    index=False
)

yield_summary.to_csv(
    OUTPUT_DIR / "des_season_yield_summary.csv",
    index=False
)

total_summary.to_csv(
    OUTPUT_DIR / "des_total_vs_upag_summary.csv",
    index=False
)

seasonal_sum_summary.to_csv(
    OUTPUT_DIR / "des_seasonal_sum_vs_upag_summary.csv",
    index=False
)

candidate_results.to_csv(
    OUTPUT_DIR / "des_upag_candidate_methods.csv",
    index=False
)

best_candidates.to_csv(
    OUTPUT_DIR / "des_upag_best_candidates.csv",
    index=False
)

example_results.to_csv(
    OUTPUT_DIR / "des_upag_example_districts.csv",
    index=False
)

total_vs_seasons_summary.to_csv(
    OUTPUT_DIR / "des_total_vs_season_sum_summary.csv",
    index=False
)

print("All investigation results exported successfully.")

All investigation results exported successfully.

In [ ]:
#Final notebook summary
print("DES ↔ UPAg SEASON INVESTIGATION COMPLETE")

print("\nValidation crops:")
print(", ".join(VALIDATION_CROPS))

print("\nCandidate representations tested:")
print("- Individual DES seasons")
print("- DES Total")
print("- Sum of Kharif + Rabi + Summer + Autumn + Winter")

print("\nImportant:")
print(
    "The automatically ranked candidate is NOT automatically accepted."
)

print(
    "\nReview the candidate_results, best_candidates, "
    "and example_results tables before finalizing the mapping."
)

====================================================================================================
DES ↔ UPAg SEASON INVESTIGATION COMPLETE
====================================================================================================

Validation crops:
Rice, Wheat, Maize, Urad

Candidate representations tested:
- Individual DES seasons
- DES Total
- Sum of Kharif + Rabi + Summer + Autumn + Winter

Important:
The automatically ranked candidate is NOT automatically accepted.

Review the candidate_results, best_candidates, and example_results tables before finalizing the mapping.