In [1]:
from pathlib import Path
import pandas as pd

# Current notebook directory
NOTEBOOK_DIR = Path.cwd()

# Project root: ...\Dump
PROJECT_ROOT = NOTEBOOK_DIR.parent

# Data directories
RAW = PROJECT_ROOT / "data" / "raw"
PROCESSED = PROJECT_ROOT / "data" / "processed"

# Input files
DES_FILE = PROCESSED / "des" / "des_harmonized.csv"
UPAG_FILE = PROCESSED / "upag_harmonized.csv"

print("Current directory :", NOTEBOOK_DIR)
print("Project root      :", PROJECT_ROOT)
print("Processed path    :", PROCESSED)

print("\nExpected input files:")
print("DES  :", DES_FILE)
print("UPAg :", UPAG_FILE)

print("\nSetup complete.")

Current directory : d:\Projects\AgriRisk and ROI Prediction\Dump\notebooks
Project root      : d:\Projects\AgriRisk and ROI Prediction\Dump
Processed path    : d:\Projects\AgriRisk and ROI Prediction\Dump\data\processed

Expected input files:
DES  : d:\Projects\AgriRisk and ROI Prediction\Dump\data\processed\des\des_harmonized.csv
UPAg : d:\Projects\AgriRisk and ROI Prediction\Dump\data\processed\upag_harmonized.csv

Setup complete.

In [6]:
print("LOCATING HARMONIZED DATASETS")

# Searching the complete processed-data directory
all_csvs = list(PROJECT_ROOT.rglob("*.csv"))

print(f"Processed CSV files found: {len(all_csvs)}")

for f in all_csvs:
    print(" -", f.relative_to(PROJECT_ROOT))

# Locating DES and UPAg files by filename
des_matches = [
    f for f in all_csvs
    if "des" in f.name.lower() and "harmon" in f.name.lower()
]

upag_matches = [
    f for f in all_csvs
    if "upag" in f.name.lower() and "harmon" in f.name.lower()
]

print("\nDES candidates:")
for f in des_matches:
    print(" ✓", f)

print("\nUPAg candidates:")
for f in upag_matches:
    print(" ✓", f)

LOCATING HARMONIZED DATASETS
Processed CSV files found: 31
 - data\processed\upag_harmonized.csv
 - data\raw\des\des_apy_raw.csv
 - data\raw\upag\rice_upag_raw.csv
 - data\raw\upag\wheat_upag_raw.csv
 - data\raw\upag\maize_upag_raw.csv
 - data\raw\upag\urad_upag_raw.csv
 - data\processed\crop_yield\des_apy_2013_14_2022_23.csv
 - data\processed\crop_yield\upag_2022_23_2024_25.csv
 - data\processed\crop_yield\arhar_des_1997_98_2022_23.csv
 - data\processed\crop_yield\bajra_des_1997_98_2022_23.csv
 - data\processed\crop_yield\jowar_des_1997_98_2022_23.csv
 - data\processed\crop_yield\gram_des_1997_98_2022_23.csv
 - data\processed\crop_yield\moong_des_1997_98_2022_23.csv
 - data\processed\crop_yield\soybean_des_1997_98_2022_23.csv
 - data\processed\crop_yield\groundnut_des_1997_98_2022_23.csv
 - data\processed\crop_yield\rapeseed_mustard_des_1997_98_2022_23.csv
 - data\processed\validation\des_upag_validation_summary.csv
 - data\processed\validation\des_upag_match_summary.csv
 - data\processed\validation\des_upag_matched_2022_23.csv
 - data\processed\validation\des_season_distribution_2022_23.csv
 - data\processed\validation\des_season_comparison_summary.csv
 - data\processed\validation\des_season_tolerance_10pct.csv
 - data\processed\validation\des_season_yield_summary.csv
 - data\processed\validation\des_total_vs_upag_summary.csv
 - data\processed\validation\des_seasonal_sum_vs_upag_summary.csv
 - data\processed\validation\des_upag_candidate_methods.csv
 - data\processed\validation\des_upag_best_candidates.csv
 - data\processed\validation\des_upag_example_districts.csv
 - data\processed\validation\des_total_vs_season_sum_summary.csv
 - data\processed\upag_harmonized\upag_crop_yield_harmonized_2022_23_2024_25.csv
 - data\processed\upag_harmonized\upag_unit_yield_validation.csv

DES candidates:

UPAg candidates:
 ✓ d:\Projects\AgriRisk and ROI Prediction\Dump\data\processed\upag_harmonized.csv
 ✓ d:\Projects\AgriRisk and ROI Prediction\Dump\data\processed\upag_harmonized\upag_crop_yield_harmonized_2022_23_2024_25.csv

In [7]:
print("INSPECTING DES AND UPAg CANDIDATE FILES")

# DES candidates: processed crop-yield datasets
des_candidates = [
    f for f in all_csvs
    if "processed" in str(f).lower()
    and "crop_yield" in str(f).lower()
    and "des" in f.name.lower()
]

# UPAg candidates
upag_candidates = [
    f for f in all_csvs
    if "upag" in f.name.lower()
    and "processed" in str(f).lower()
]

print("\nDES CANDIDATES")
print("-" * 80)

for f in des_candidates:
    temp = pd.read_csv(f, nrows=3)
    print(f"\nFile: {f.relative_to(PROJECT_ROOT)}")
    print("Columns:", list(temp.columns))

print("\nUPAg CANDIDATES")
print("-" * 80)

for f in upag_candidates:
    temp = pd.read_csv(f, nrows=3)
    print(f"\nFile: {f.relative_to(PROJECT_ROOT)}")
    print("Columns:", list(temp.columns))

INSPECTING DES AND UPAg CANDIDATE FILES

DES CANDIDATES
--------------------------------------------------------------------------------

File: data\processed\crop_yield\des_apy_2013_14_2022_23.csv
Columns: ['state', 'state_code', 'district', 'district_code', 'crop', 'crop_source_name', 'crop_code', 'crop_type', 'season', 'year', 'area_ha', 'production_tonnes', 'yield_tonnes_ha', 'yield_kg_ha', 'yield_quintal_acre', 'data_source']

File: data\processed\crop_yield\arhar_des_1997_98_2022_23.csv
Columns: ['crop', 'file', 'column', 'keyword']

File: data\processed\crop_yield\bajra_des_1997_98_2022_23.csv
Columns: ['crop', 'file', 'column', 'keyword']

File: data\processed\crop_yield\jowar_des_1997_98_2022_23.csv
Columns: ['crop', 'file', 'column', 'keyword']

File: data\processed\crop_yield\gram_des_1997_98_2022_23.csv
Columns: ['crop', 'file', 'column', 'keyword']

File: data\processed\crop_yield\moong_des_1997_98_2022_23.csv
Columns: ['crop', 'file', 'column', 'keyword']

File: data\processed\crop_yield\soybean_des_1997_98_2022_23.csv
Columns: ['crop', 'file', 'column', 'keyword']

File: data\processed\crop_yield\groundnut_des_1997_98_2022_23.csv
Columns: ['crop', 'file', 'column', 'keyword']

File: data\processed\crop_yield\rapeseed_mustard_des_1997_98_2022_23.csv
Columns: ['year', 'state', 'state_code', 'district', 'district_code', 'crop_source_name', 'crop_code', 'crop_type', 'season', 'area_ha', 'area_unit', 'production_tonnes', 'production_unit', 'yield_reported', 'yield_unit', 'crop']

UPAg CANDIDATES
--------------------------------------------------------------------------------

File: data\processed\upag_harmonized.csv
Columns: ['year', 'state', 'district', 'lgd_distcode', 'lgd_statecode', 'crop', 'area', 'production', 'yield']

File: data\processed\crop_yield\upag_2022_23_2024_25.csv
Columns: ['state', 'state_code', 'district', 'district_code', 'census_code', 'crop', 'crop_source_name', 'year', 'area_lakh_ha', 'area_ha', 'production_lakh_tonnes', 'production_tonnes', 'yield_kg_ha', 'yield_tonnes_ha', 'yield_quintal_acre', 'data_source']

File: data\processed\validation\des_upag_validation_summary.csv
Columns: ['crop', 'matched_observations', 'mean_area_difference_pct', 'median_area_difference_pct', 'mean_production_difference_pct', 'median_production_difference_pct', 'mean_yield_difference_pct', 'median_yield_difference_pct']

File: data\processed\validation\des_upag_match_summary.csv
Columns: ['crop', 'total_comparison_rows', 'matched', 'des_only', 'upag_only', 'match_percentage']

File: data\processed\validation\des_upag_matched_2022_23.csv
Columns: ['state_des', 'state_code', 'district_des', 'district_code', 'crop', 'crop_source_name_des', 'crop_code', 'crop_type', 'season', 'year_des', 'area_ha_des', 'production_tonnes_des', 'yield_tonnes_ha_des', 'yield_kg_ha_des', 'yield_quintal_acre_des', 'data_source_des', 'comparison_season', 'state_upag', 'district_upag', 'census_code', 'crop_source_name_upag', 'year_upag', 'area_lakh_ha', 'area_ha_upag', 'production_lakh_tonnes', 'production_tonnes_upag', 'yield_kg_ha_upag', 'yield_tonnes_ha_upag', 'yield_quintal_acre_upag', 'data_source_upag', '_merge', 'area_difference', 'production_difference', 'yield_difference', 'area_difference_pct', 'production_difference_pct', 'yield_difference_pct']

File: data\processed\validation\des_total_vs_upag_summary.csv
Columns: ['crop', 'matched_districts', 'median_area_diff_pct', 'mean_area_diff_pct', 'median_production_diff_pct', 'mean_production_diff_pct', 'median_yield_diff_pct', 'mean_yield_diff_pct']

File: data\processed\validation\des_seasonal_sum_vs_upag_summary.csv
Columns: ['crop', 'matched_districts', 'median_area_diff_pct', 'mean_area_diff_pct', 'median_production_diff_pct', 'mean_production_diff_pct', 'median_yield_diff_pct', 'mean_yield_diff_pct']

File: data\processed\validation\des_upag_candidate_methods.csv
Columns: ['crop', 'representation', 'method_type', 'matched_districts', 'median_area_diff_pct', 'mean_area_diff_pct', 'median_production_diff_pct', 'mean_production_diff_pct', 'median_yield_diff_pct', 'mean_yield_diff_pct']

File: data\processed\validation\des_upag_best_candidates.csv
Columns: ['crop', 'representation', 'method_type', 'matched_districts', 'median_area_diff_pct', 'mean_area_diff_pct', 'median_production_diff_pct', 'mean_production_diff_pct', 'median_yield_diff_pct', 'mean_yield_diff_pct', 'combined_median_score']

File: data\processed\validation\des_upag_example_districts.csv
Columns: ['crop', 'state', 'district', 'des_season', 'des_area_ha', 'upag_area_ha', 'des_production_tonnes', 'upag_production_tonnes', 'des_yield_kg_ha', 'upag_yield_kg_ha', 'area_diff_pct', 'production_diff_pct', 'yield_diff_pct']

File: data\processed\upag_harmonized\upag_crop_yield_harmonized_2022_23_2024_25.csv
Columns: ['state', 'district', 'state_code', 'district_code', 'crop', 'year', 'area_ha', 'production_tonnes', 'yield_kg_ha']

File: data\processed\upag_harmonized\upag_unit_yield_validation.csv
Columns: ['crop', 'observations', 'median_reported_yield', 'median_calculated_yield', 'median_yield_difference', 'mean_yield_difference_pct', 'max_yield_difference_pct']

In [8]:
print("LOADING DES AND UPAg HARMONIZED DATA")

# Actual DES dataset
DES_FILE = PROJECT_ROOT / "data" / "processed" / "crop_yield" / "des_apy_2013_14_2022_23.csv"

# Actual UPAg harmonized dataset
UPAG_FILE = PROJECT_ROOT / "data" / "processed" / "upag_harmonized.csv"

des = pd.read_csv(DES_FILE)
upag = pd.read_csv(UPAG_FILE)

print("\nDES")
print("Shape:", des.shape)
print("Columns:", list(des.columns))

print("\nUPAg")
print("Shape:", upag.shape)
print("Columns:", list(upag.columns))

print("\n✓ Both datasets loaded successfully")

LOADING DES AND UPAg HARMONIZED DATA

DES
Shape: (85920, 16)
Columns: ['state', 'state_code', 'district', 'district_code', 'crop', 'crop_source_name', 'crop_code', 'crop_type', 'season', 'year', 'area_ha', 'production_tonnes', 'yield_tonnes_ha', 'yield_kg_ha', 'yield_quintal_acre', 'data_source']

UPAg
Shape: (9384, 9)
Columns: ['year', 'state', 'district', 'lgd_distcode', 'lgd_statecode', 'crop', 'area', 'production', 'yield']

✓ Both datasets loaded successfully

In [9]:
print("COMPARING DES AND UPAg COVERAGE")

print("\nDES crops:")
print(sorted(des["crop"].dropna().unique()))

print("\nUPAg crops:")
print(sorted(upag["crop"].dropna().unique()))

print("\nDES year range:")
print(des["year"].min(), "to", des["year"].max())

print("\nUPAg year range:")
print(upag["year"].min(), "to", upag["year"].max())

COMPARING DES AND UPAg COVERAGE

DES crops:
['Arhar/Tur', 'Bajra', 'Gram', 'Groundnut', 'Jowar', 'Maize', 'Ragi', 'Rice', 'Soyabean', 'Sugarcane', 'Urad', 'Wheat']

UPAg crops:
['Maize', 'Rice', 'Urad', 'Wheat']

DES year range:
2013-2014 to 2022-2023

UPAg year range:
2022-23 to 2024-25

In [10]:
print("IDENTIFYING COMMON CROPS AND OVERLAPPING YEARS")

common_crops = sorted(set(des["crop"]) & set(upag["crop"]))
common_years = sorted(set(des["year"]) & set(upag["year"]))

print("\nCommon crops:")
for crop in common_crops:
    print("✓", crop)

print("\nOverlapping years:")
for year in common_years:
    print("✓", year)

print("\nCommon crop count :", len(common_crops))
print("Common year count :", len(common_years))

IDENTIFYING COMMON CROPS AND OVERLAPPING YEARS

Common crops:
✓ Maize
✓ Rice
✓ Urad
✓ Wheat

Overlapping years:

Common crop count : 4
Common year count : 0

In [11]:
print("NORMALIZING YEAR FORMATS")

def normalize_year(x):
    x = str(x).strip()
    
    if "-" not in x:
        return x
    
    start, end = x.split("-", 1)
    
    # Converting YYYY-YY → YYYY-YYYY
    if len(start) == 4 and len(end) == 2:
        end = start[:2] + end
    
    return f"{start}-{end}"

des["year_normalized"] = des["year"].apply(normalize_year)
upag["year_normalized"] = upag["year"].apply(normalize_year)

print("DES years   :", sorted(des["year_normalized"].unique()))
print("UPAg years  :", sorted(upag["year_normalized"].unique()))

common_years = sorted(
    set(des["year_normalized"]) & set(upag["year_normalized"])
)

print("\nCommon years:", common_years)
print("Common year count:", len(common_years))

NORMALIZING YEAR FORMATS
DES years   : ['2013-2014', '2014-2015', '2015-2016', '2016-2017', '2017-2018', '2018-2019', '2019-2020', '2020-2021', '2021-2022', '2022-2023']
UPAg years  : ['2022-2023', '2023-2024', '2024-2025']

Common years: ['2022-2023']
Common year count: 1

In [14]:
print("NORMALIZING YEARS AND CREATING COMPARISON SUBSETS")

def normalize_year(x):
    x = str(x).strip()
    if "-" in x:
        a, b = x.split("-")
        if len(b) == 2:
            b = a[:2] + b
        return f"{a}-{b}"
    return x

des["year"] = des["year"].apply(normalize_year)
upag["year"] = upag["year"].apply(normalize_year)

common_crops = ["Maize", "Rice", "Urad", "Wheat"]
common_year = "2022-2023"

des_common = des[
    des["crop"].isin(common_crops) &
    (des["year"] == common_year)
].copy()

upag_common = upag[
    upag["crop"].isin(common_crops) &
    (upag["year"] == common_year)
].copy()

print("DES comparison rows  :", len(des_common))
print("UPAg comparison rows :", len(upag_common))

print("\nDES crop counts:")
print(des_common["crop"].value_counts().sort_index())

print("\nUPAg crop counts:")
print(upag_common["crop"].value_counts().sort_index())

print("\nComparison subsets created successfully.")

NORMALIZING YEARS AND CREATING COMPARISON SUBSETS
DES comparison rows  : 5009
UPAg comparison rows : 3128

DES crop counts:
crop
Maize    1599
Rice     1578
Urad     1269
Wheat     563
Name: count, dtype: int64

UPAg crop counts:
crop
Maize    782
Rice     782
Urad     782
Wheat    782
Name: count, dtype: int64

Comparison subsets created successfully.

In [15]:
print("AGGREGATING DES SEASONAL DATA TO ANNUAL DISTRICT LEVEL")

# Annual aggregation of DES (sum area & production across seasons)
des_annual = (
    des_common
    .groupby(
        ["year", "state", "district", "crop"],
        as_index=False
    )
    .agg({
        "area_ha": "sum",
        "production_tonnes": "sum"
    })
)

# Recalculating annual yield
des_annual["yield_kg_ha"] = (
    des_annual["production_tonnes"] /
    des_annual["area_ha"]
) * 1000

# Renaming columns to match UPAg naming
des_annual = des_annual.rename(columns={
    "area_ha": "area",
    "production_tonnes": "production",
    "yield_kg_ha": "yield"
})

print("DES seasonal rows :", len(des_common))
print("DES annual rows   :", len(des_annual))

print("\nCrop-wise annual records:")
print(des_annual["crop"].value_counts().sort_index())

print("\nSample annual DES data:")
display(des_annual.head())

AGGREGATING DES SEASONAL DATA TO ANNUAL DISTRICT LEVEL
DES seasonal rows : 5009
DES annual rows   : 2464

Crop-wise annual records:
crop
Maize    655
Rice     675
Urad     581
Wheat    553
Name: count, dtype: int64

Sample annual DES data:

,year,state,district,crop,area,production,yield
0,2022-2023,Andaman And Nicobar Islands,Nicobars,Rice,1.00,1.26,1260.000000
1,2022-2023,Andaman And Nicobar Islands,North And Middle Andaman,Maize,15.14,34.22,2260.237781
2,2022-2023,Andaman And Nicobar Islands,North And Middle Andaman,Rice,4915.15,10369.04,2109.608049
3,2022-2023,Andaman And Nicobar Islands,North And Middle Andaman,Urad,330.20,118.08,357.601454
4,2022-2023,Andaman And Nicobar Islands,South Andamans,Rice,73.50,153.06,2082.448980

In [16]:
print("STANDARDIZING STATE AND DISTRICT NAMES")

def clean_location(series):
    return (
        series.astype(str)
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
        .str.lower()
    )

for df in [des_annual, upag_common]:
    df["state_key"] = clean_location(df["state"])
    df["district_key"] = clean_location(df["district"])

print("DES unique states     :", des_annual["state_key"].nunique())
print("UPAg unique states    :", upag_common["state_key"].nunique())
print("DES unique districts  :", des_annual["district_key"].nunique())
print("UPAg unique districts :", upag_common["district_key"].nunique())

print("\nGeographic keys created successfully.")

STANDARDIZING STATE AND DISTRICT NAMES
DES unique states     : 34
UPAg unique states    : 36
DES unique districts  : 725
UPAg unique districts : 779

Geographic keys created successfully.

In [17]:
print("MATCHING DES AND UPAg RECORDS")

match_keys = ["year", "state_key", "district_key", "crop"]

des_keys = des_annual[match_keys].drop_duplicates()
upag_keys = upag_common[match_keys].drop_duplicates()

matched_keys = des_keys.merge(
    upag_keys,
    on=match_keys,
    how="inner"
)

print("DES annual records :", len(des_keys))
print("UPAg records       :", len(upag_keys))
print("Exact matches      :", len(matched_keys))

print("\nMatches by crop:")
print(matched_keys["crop"].value_counts().sort_index())

print("\nExact geographic matching completed.")

MATCHING DES AND UPAg RECORDS
DES annual records : 2464
UPAg records       : 3128
Exact matches      : 2393

Matches by crop:
crop
Maize    636
Rice     656
Urad     563
Wheat    538
Name: count, dtype: int64

Exact geographic matching completed.

In [18]:
print("CREATING DES–UPAg HARMONIZED COMPARISON DATA")

des_compare = des_annual.merge(
    upag_common[
        ["year", "state_key", "district_key", "crop",
         "area", "production", "yield"]
    ],
    on=["year", "state_key", "district_key", "crop"],
    how="inner",
    suffixes=("_des", "_upag")
)

print("Matched comparison rows :", len(des_compare))
print("Crops                  :", des_compare["crop"].unique())

print("\nColumns:")
print(des_compare.columns.tolist())

display(des_compare.head())

CREATING DES–UPAg HARMONIZED COMPARISON DATA
Matched comparison rows : 2393
Crops                  : ['Rice' 'Maize' 'Urad' 'Wheat']

Columns:
['year', 'state', 'district', 'crop', 'area_des', 'production_des', 'yield_des', 'state_key', 'district_key', 'area_upag', 'production_upag', 'yield_upag']

,year,state,district,crop,area_des,production_des,yield_des,state_key,district_key,area_upag,production_upag,yield_upag
0,2022-2023,Andaman And Nicobar Islands,Nicobars,Rice,1.00,1.26,1260.000000,andaman and nicobar islands,nicobars,0.00,0.0,1260.0
1,2022-2023,Andaman And Nicobar Islands,North And Middle Andaman,Maize,15.14,34.22,2260.237781,andaman and nicobar islands,north and middle andaman,0.00,0.0,2260.0
2,2022-2023,Andaman And Nicobar Islands,North And Middle Andaman,Rice,4915.15,10369.04,2109.608049,andaman and nicobar islands,north and middle andaman,0.05,0.1,2110.0
3,2022-2023,Andaman And Nicobar Islands,North And Middle Andaman,Urad,330.20,118.08,357.601454,andaman and nicobar islands,north and middle andaman,0.00,0.0,358.0
4,2022-2023,Andaman And Nicobar Islands,South Andamans,Rice,73.50,153.06,2082.448980,andaman and nicobar islands,south andamans,0.00,0.0,2082.0

In [19]:
print("CALCULATING DES–UPAg DIFFERENCES")

for metric in ["area", "production", "yield"]:
    des_compare[f"{metric}_diff"] = (
        des_compare[f"{metric}_upag"] -
        des_compare[f"{metric}_des"]
    )

    des_compare[f"{metric}_diff_pct"] = (
        des_compare[f"{metric}_diff"] /
        des_compare[f"{metric}_des"].replace(0, pd.NA)
    ) * 100

print("Difference calculations completed.")

display(des_compare[
    ["year", "state", "district", "crop",
     "area_des", "area_upag", "area_diff_pct",
     "production_des", "production_upag", "production_diff_pct",
     "yield_des", "yield_upag", "yield_diff_pct"]
].head())

CALCULATING DES–UPAg DIFFERENCES
Difference calculations completed.

,year,state,district,crop,area_des,area_upag,area_diff_pct,production_des,production_upag,production_diff_pct,yield_des,yield_upag,yield_diff_pct
0,2022-2023,Andaman And Nicobar Islands,Nicobars,Rice,1.00,0.00,-100.000000,1.26,0.0,-100.0,1260.000000,1260.0,0.0
1,2022-2023,Andaman And Nicobar Islands,North And Middle Andaman,Maize,15.14,0.00,-100.000000,34.22,0.0,-100.0,2260.237781,2260.0,-0.01052
2,2022-2023,Andaman And Nicobar Islands,North And Middle Andaman,Rice,4915.15,0.05,-99.998983,10369.04,0.1,-99.999036,2109.608049,2110.0,0.018579
3,2022-2023,Andaman And Nicobar Islands,North And Middle Andaman,Urad,330.20,0.00,-100.000000,118.08,0.0,-100.0,357.601454,358.0,0.11145
4,2022-2023,Andaman And Nicobar Islands,South Andamans,Rice,73.50,0.00,-100.000000,153.06,0.0,-100.0,2082.448980,2082.0,-0.02156

In [20]:
print("DES–UPAg CROP-WISE COMPARISON SUMMARY")

summary = (
    des_compare
    .groupby("crop")
    .agg(
        matched_rows=("crop", "size"),
        mean_area_diff_pct=("area_diff_pct", "mean"),
        median_area_diff_pct=("area_diff_pct", "median"),
        mean_production_diff_pct=("production_diff_pct", "mean"),
        median_production_diff_pct=("production_diff_pct", "median"),
        mean_yield_diff_pct=("yield_diff_pct", "mean"),
        median_yield_diff_pct=("yield_diff_pct", "median")
    )
    .reset_index()
)

display(summary.round(2))

DES–UPAg CROP-WISE COMPARISON SUMMARY

,crop,matched_rows,mean_area_diff_pct,median_area_diff_pct,mean_production_diff_pct,median_production_diff_pct,mean_yield_diff_pct,median_yield_diff_pct
0,Maize,636,-100.0,-100.0,-99.999412,-99.999499,0.000485,0.0
1,Rice,656,-100.0,-100.0,-99.999308,-99.999499,0.122299,0.000025
2,Urad,563,-100.0,-100.0,-99.999601,-99.999548,0.181384,0.0
3,Wheat,538,-100.0,-100.0,-99.99919,-99.999001,-0.000448,0.0

In [21]:
print("DES–UPAg MATCHING SUMMARY")

total_des = len(des_annual)
matched = len(des_compare)

print(f"DES annual records : {total_des}")
print(f"Matched records    : {matched}")
print(f"Unmatched records  : {total_des - matched}")
print(f"Match rate         : {matched / total_des * 100:.2f}%")

print("\nMatched records by crop:")
print(
    des_compare["crop"]
    .value_counts()
    .sort_index()
)

print("\nComparison period : 2022-2023")
print("Comparison crops  : Maize, Rice, Urad, Wheat")

DES–UPAg MATCHING SUMMARY
DES annual records : 2464
Matched records    : 2393
Unmatched records  : 71
Match rate         : 97.12%

Matched records by crop:
crop
Maize    636
Rice     656
Urad     563
Wheat    538
Name: count, dtype: int64

Comparison period : 2022-2023
Comparison crops  : Maize, Rice, Urad, Wheat

In [25]:
print("AVAILABLE DES–UPAg COMPARISON DATAFRAME")

for name, obj in list(globals().items()):
    if isinstance(obj, pd.DataFrame):
        cols = set(obj.columns)
        if {"area_upag", "production_upag", "yield_upag"}.issubset(cols):
            print(f"✓ {name} -> {obj.shape}")

AVAILABLE DES–UPAg COMPARISON DATAFRAME
✓ des_compare -> (2393, 18)

In [26]:
print("CLASSIFYING UPAg OBSERVATIONS")

for col in ["area_upag", "production_upag", "yield_upag"]:
    des_compare[col + "_status"] = des_compare[col].apply(
        lambda x: "missing" if pd.isna(x)
        else "zero" if x == 0
        else "valid"
    )

status_summary = des_compare.groupby("crop")[
    ["area_upag_status", "production_upag_status", "yield_upag_status"]
].agg(lambda x: x.value_counts().to_dict())

display(status_summary)

print("\nObservation classification complete.")

CLASSIFYING UPAg OBSERVATIONS

,area_upag_status,production_upag_status,yield_upag_status
crop,,,
Maize,"{'valid': 485, 'zero': 151}","{'valid': 544, 'zero': 92}",{'valid': 636}
Rice,"{'valid': 621, 'zero': 35}","{'valid': 628, 'zero': 28}",{'valid': 656}
Urad,"{'valid': 353, 'zero': 210}","{'valid': 305, 'zero': 258}","{'valid': 559, 'zero': 4}"
Wheat,"{'valid': 403, 'zero': 135}","{'valid': 427, 'zero': 111}",{'valid': 538}

Observation classification complete.

In [27]:
print("CALCULATING VALID DES–UPAg DIFFERENCES")

for metric in ["area", "production", "yield"]:
    des_col = metric + "_des"
    upag_col = metric + "_upag"
    diff_col = metric + "_diff_pct"

    valid = (
        des_compare[des_col].notna() &
        des_compare[upag_col].notna() &
        (des_compare[upag_col] > 0)
    )

    des_compare.loc[valid, diff_col] = (
        (des_compare.loc[valid, upag_col] -
         des_compare.loc[valid, des_col])
        / des_compare.loc[valid, des_col].replace(0, pd.NA)
    ) * 100

print("Valid difference calculations completed.")

display(
    des_compare[
        ["crop",
         "area_diff_pct",
         "production_diff_pct",
         "yield_diff_pct"]
    ].describe()
)

CALCULATING VALID DES–UPAg DIFFERENCES
Valid difference calculations completed.

       area_diff_pct
count    2393.000000
mean      -99.999394
std         0.000408
min      -100.000000
25%       -99.999544
50%       -99.999489
75%       -99.999001
max       -99.998000

In [29]:
print("DES vs UPAg VALUE SCALE CHECK")

scale_check = des_compare.groupby("crop").agg(
    des_area_median=("area_des", "median"),
    upag_area_median=("area_upag", "median"),
    des_production_median=("production_des", "median"),
    upag_production_median=("production_upag", "median"),
    des_yield_median=("yield_des", "median"),
    upag_yield_median=("yield_upag", "median")
)

display(scale_check)

DES vs UPAg VALUE SCALE CHECK

,des_area_median,upag_area_median,des_production_median,upag_production_median,des_yield_median,upag_yield_median
crop,,,,,,
Maize,4498.0,0.030,11550.000,0.07,2757.352941,2757.5
Rice,76052.5,0.485,203386.000,1.33,2717.878467,2718.0
Urad,1738.0,0.010,971.000,0.01,668.562761,669.0
Wheat,29025.0,0.290,70930.928,0.71,2549.304866,2549.5

In [30]:
print("VALID YIELD COMPARISON")

valid_yield = (
    des_compare["yield_des"].notna() &
    des_compare["yield_upag"].notna()
)

des_compare["yield_diff_pct"] = (
    (des_compare["yield_upag"] - des_compare["yield_des"])
    / des_compare["yield_des"].replace(0, pd.NA)
) * 100

yield_summary = des_compare[valid_yield].groupby("crop").agg(
    matched_rows=("yield_des", "size"),
    mean_yield_diff_pct=("yield_diff_pct", "mean"),
    median_yield_diff_pct=("yield_diff_pct", "median"),
    mean_des_yield=("yield_des", "mean"),
    mean_upag_yield=("yield_upag", "mean")
).reset_index()

display(yield_summary.round(4))

print("\nArea and production scale discrepancy retained for documentation.")
print("No arbitrary unit conversion applied.")

VALID YIELD COMPARISON

,crop,matched_rows,mean_yield_diff_pct,median_yield_diff_pct,mean_des_yield,mean_upag_yield
0,Maize,636,0.000485,0.0,3362.2659,3362.2704
1,Rice,656,0.122299,0.000025,2767.6073,2771.6296
2,Urad,563,0.181384,0.0,690.6502,692.4316
3,Wheat,538,-0.000448,0.0,2754.8454,2754.8401

Area and production scale discrepancy retained for documentation.
No arbitrary unit conversion applied.

In [31]:
print("FINAL DES–UPAg COMPARISON SUMMARY")

final_summary = yield_summary.copy()

final_summary["match_rate_pct"] = (
    final_summary["matched_rows"]
    / des_compare.groupby("crop").size().values
) * 100

display(final_summary.round(4))

print("\nComparison year : 2022-2023")
print("Comparison crops: Maize, Rice, Urad, Wheat")
print("Area/production: scale discrepancy retained; no arbitrary conversion applied.")
print("Yield comparison: completed successfully.")

FINAL DES–UPAg COMPARISON SUMMARY

,crop,matched_rows,mean_yield_diff_pct,median_yield_diff_pct,mean_des_yield,mean_upag_yield,match_rate_pct
0,Maize,636,0.000485,0.0,3362.2659,3362.2704,100.0
1,Rice,656,0.122299,0.000025,2767.6073,2771.6296,100.0
2,Urad,563,0.181384,0.0,690.6502,692.4316,100.0
3,Wheat,538,-0.000448,0.0,2754.8454,2754.8401,100.0

Comparison year : 2022-2023
Comparison crops: Maize, Rice, Urad, Wheat
Area/production: scale discrepancy retained; no arbitrary conversion applied.
Yield comparison: completed successfully.

In [34]:
print("NOTEBOOK 07 — FINAL QUALITY CHECK")

total = len(des_annual)
matched = len(des_compare)
unmatched = total - matched

print(f"DES annual records : {total}")
print(f"Matched records    : {matched}")
print(f"Unmatched records  : {unmatched}")
print(f"Overall match rate : {matched / total * 100:.2f}%")

print("\nComparison crops:", sorted(des_compare["crop"].unique()))
print("Comparison year :", sorted(des_compare["year"].unique()))

print("\nYield comparison:")
print(final_summary[
    ["crop", "matched_rows",
     "mean_yield_diff_pct",
     "median_yield_diff_pct"]
].round(4).to_string(index=False))

print("\n✓ Geographic matching validated")
print("✓ Yield comparison validated")
print("✓ Original DES and UPAg values preserved")
print("✓ No arbitrary area/production conversion applied")
print("✓ NOTEBOOK 07 VALIDATION COMPLETE")

NOTEBOOK 07 — FINAL QUALITY CHECK
DES annual records : 2464
Matched records    : 2393
Unmatched records  : 71
Overall match rate : 97.12%

Comparison crops: ['Maize', 'Rice', 'Urad', 'Wheat']
Comparison year : ['2022-2023']

Yield comparison:
 crop  matched_rows mean_yield_diff_pct median_yield_diff_pct
Maize           636            0.000485                   0.0
 Rice           656            0.122299              0.000025
 Urad           563            0.181384                   0.0
Wheat           538           -0.000448                   0.0

✓ Geographic matching validated
✓ Yield comparison validated
✓ Original DES and UPAg values preserved
✓ No arbitrary area/production conversion applied
✓ NOTEBOOK 07 VALIDATION COMPLETE